upstream nexus {
    server nexus:8081;
}

upstream docker-hosted {
    server nexus:8082;
}

upstream docker-group {
    server nexus:8083;
}

server {
    listen 80;
    server_name nexus.local;

    client_max_body_size 1G;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Nexus UI + REST API
    location / {
        proxy_pass http://nexus;
    }
}

# Docker hosted registry (push)
server {
    listen 80;
    server_name docker-hosted.local;

    client_max_body_size 2G;
    chunked_transfer_encoding on;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        proxy_pass http://docker-hosted;
    }
}

# Docker group registry (pull)
server {
    listen 80;
    server_name docker-group.local;

    client_max_body_size 2G;
    chunked_transfer_encoding on;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        proxy_pass http://docker-group;
    }
}
