jenkins:
  systemMessage: "Git Provider Jenkins (CasC managed)"
  numExecutors: 2
  mode: NORMAL
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
