server:
  port: 18080

spring:
  application:
    name: spring-grpc-client

# gRPC Client Configuration
grpc:
  client:
    git-provider:
      address: static://localhost:50051
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
