spring:
  datasource:
    url: jdbc:h2:mem:querydsl;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: true

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: false
      slow-query:
        enable-logging: false

logging:
  level:
    root: warn
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: warn
    org.hibernate.orm.jdbc.bind: trace
    com.runnershigh: info
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n"
