services:
  alloy:
    build:
      context: .
      dockerfile: ./images/alloy/Dockerfile
    container_name: obs-minimal-alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    depends_on:
      - loki
      - tempo

  loki:
    build:
      context: .
      dockerfile: ./images/loki/Dockerfile
    container_name: obs-minimal-loki
    command:
      - -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"

  tempo:
    build:
      context: .
      dockerfile: ./images/tempo/Dockerfile
    container_name: obs-minimal-tempo
    command:
      - -config.file=/etc/tempo/config.yml
    ports:
      - "3200:3200"
      - "4320:4317"

  grafana:
    build:
      context: .
      dockerfile: ./images/grafana/Dockerfile
    container_name: obs-minimal-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - tempo

  sample-app:
    build:
      context: ./sample-app
    container_name: obs-minimal-sample-app
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://alloy:4318/v1/logs
      - OTEL_SERVICE_NAME=simple-practice-app
      - OTEL_DEPLOYMENT_ENV=practice
    ports:
      - "18080:8080"
    depends_on:
      - alloy
