### 리포지토리 전체 목록
GET http://localhost:8081/service/rest/v1/repositories
Authorization: Basic YWRtaW46YWRtaW4xMjM=
Accept: application/json

### 특정 리포지토리 상세 (maven-public)
GET http://localhost:8081/service/rest/v1/repositories/maven-public
Authorization: Basic YWRtaW46YWRtaW4xMjM=
Accept: application/json

### Maven Hosted 리포지토리 생성 (예시)
POST http://localhost:8081/service/rest/v1/repositories/maven/hosted
Authorization: Basic YWRtaW46YWRtaW4xMjM=
Content-Type: application/json

{
  "name": "maven-test",
  "online": true,
  "storage": {
    "blobStoreName": "default",
    "strictContentTypeValidation": true,
    "writePolicy": "ALLOW"
  },
  "maven": {
    "versionPolicy": "MIXED",
    "layoutPolicy": "STRICT"
  }
}
