### 리포지토리 에셋 목록
GET http://localhost:8081/service/rest/v1/assets?repository=raw-hosted
Authorization: Basic YWRtaW46YWRtaW4xMjM=
Accept: application/json

### 특정 에셋 상세
# GET http://localhost:8081/service/rest/v1/assets/{assetId}
# Authorization: Basic YWRtaW46YWRtaW4xMjM=
# Accept: application/json

### 에셋 삭제
# DELETE http://localhost:8081/service/rest/v1/assets/{assetId}
# Authorization: Basic YWRtaW46YWRtaW4xMjM=
