// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: v1/cicd.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_UNSPECIFIED BuildStatus = 0
	BuildStatus_BUILD_STATUS_QUEUED      BuildStatus = 1
	BuildStatus_BUILD_STATUS_RUNNING     BuildStatus = 2
	BuildStatus_BUILD_STATUS_SUCCESS     BuildStatus = 3
	BuildStatus_BUILD_STATUS_FAILURE     BuildStatus = 4
	BuildStatus_BUILD_STATUS_ABORTED     BuildStatus = 5
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BUILD_STATUS_UNSPECIFIED",
		1: "BUILD_STATUS_QUEUED",
		2: "BUILD_STATUS_RUNNING",
		3: "BUILD_STATUS_SUCCESS",
		4: "BUILD_STATUS_FAILURE",
		5: "BUILD_STATUS_ABORTED",
	}
	BuildStatus_value = map[string]int32{
		"BUILD_STATUS_UNSPECIFIED": 0,
		"BUILD_STATUS_QUEUED":      1,
		"BUILD_STATUS_RUNNING":     2,
		"BUILD_STATUS_SUCCESS":     3,
		"BUILD_STATUS_FAILURE":     4,
		"BUILD_STATUS_ABORTED":     5,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_cicd_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_v1_cicd_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{0}
}

type JenkinsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                           // Jenkins 서버 URL (http://jenkins:8080)
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                 // Jenkins 사용자명
	ApiToken      string                 `protobuf:"bytes,3,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"` // Jenkins API 토큰
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JenkinsConfig) Reset() {
	*x = JenkinsConfig{}
	mi := &file_v1_cicd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JenkinsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JenkinsConfig) ProtoMessage() {}

func (x *JenkinsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JenkinsConfig.ProtoReflect.Descriptor instead.
func (*JenkinsConfig) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{0}
}

func (x *JenkinsConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JenkinsConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JenkinsConfig) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

// CI 프로바이더 설정 (하나만 선택)
type CIConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*CIConfig_Jenkins
	Config        isCIConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIConfig) Reset() {
	*x = CIConfig{}
	mi := &file_v1_cicd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIConfig) ProtoMessage() {}

func (x *CIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIConfig.ProtoReflect.Descriptor instead.
func (*CIConfig) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{1}
}

func (x *CIConfig) GetConfig() isCIConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CIConfig) GetJenkins() *JenkinsConfig {
	if x != nil {
		if x, ok := x.Config.(*CIConfig_Jenkins); ok {
			return x.Jenkins
		}
	}
	return nil
}

type isCIConfig_Config interface {
	isCIConfig_Config()
}

type CIConfig_Jenkins struct {
	Jenkins *JenkinsConfig `protobuf:"bytes,1,opt,name=jenkins,proto3,oneof"` // 향후: GitHubActionsConfig, GitLabCIConfig 등
}

func (*CIConfig_Jenkins) isCIConfig_Config() {}

type PipelineStage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                            // 스테이지 이름 ("Build", "Test", "Deploy")
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                      // 실행 명령어
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 타임아웃 (초)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PipelineStage) Reset() {
	*x = PipelineStage{}
	mi := &file_v1_cicd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStage) ProtoMessage() {}

func (x *PipelineStage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStage.ProtoReflect.Descriptor instead.
func (*PipelineStage) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineStage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineStage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PipelineStage) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type Pipeline struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Repository     string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`                            // namespace/repo
	BranchPattern  string                 `protobuf:"bytes,4,opt,name=branch_pattern,json=branchPattern,proto3" json:"branch_pattern,omitempty"` // "main", "feature/*"
	Stages         []*PipelineStage       `protobuf:"bytes,5,rep,name=stages,proto3" json:"stages,omitempty"`
	CiConfig       *CIConfig              `protobuf:"bytes,6,opt,name=ci_config,json=ciConfig,proto3" json:"ci_config,omitempty"`
	JenkinsJobName string                 `protobuf:"bytes,7,opt,name=jenkins_job_name,json=jenkinsJobName,proto3" json:"jenkins_job_name,omitempty"` // Jenkins Job 이름
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_v1_cicd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{3}
}

func (x *Pipeline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Pipeline) GetBranchPattern() string {
	if x != nil {
		return x.BranchPattern
	}
	return ""
}

func (x *Pipeline) GetStages() []*PipelineStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *Pipeline) GetCiConfig() *CIConfig {
	if x != nil {
		return x.CiConfig
	}
	return nil
}

func (x *Pipeline) GetJenkinsJobName() string {
	if x != nil {
		return x.JenkinsJobName
	}
	return ""
}

func (x *Pipeline) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Pipeline) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Build struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId      string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	BuildNumber     int32                  `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	Status          BuildStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=gitprovider.v1.BuildStatus" json:"status,omitempty"`
	Trigger         string                 `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"` // "push", "mr_merged", "manual"
	Branch          string                 `protobuf:"bytes,6,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitSha       string                 `protobuf:"bytes,7,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	StartedAt       string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      string                 `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,10,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Url             string                 `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"` // Jenkins 빌드 URL
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_v1_cicd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{4}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *Build) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *Build) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *Build) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Build) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Build) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Build) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Build) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Build) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Build) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreatePipelineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repository     string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	BranchPattern  string                 `protobuf:"bytes,3,opt,name=branch_pattern,json=branchPattern,proto3" json:"branch_pattern,omitempty"`
	Stages         []*PipelineStage       `protobuf:"bytes,4,rep,name=stages,proto3" json:"stages,omitempty"`
	CiConfig       *CIConfig              `protobuf:"bytes,5,opt,name=ci_config,json=ciConfig,proto3" json:"ci_config,omitempty"`
	JenkinsJobName string                 `protobuf:"bytes,6,opt,name=jenkins_job_name,json=jenkinsJobName,proto3" json:"jenkins_job_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePipelineRequest) Reset() {
	*x = CreatePipelineRequest{}
	mi := &file_v1_cicd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRequest) ProtoMessage() {}

func (x *CreatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePipelineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePipelineRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CreatePipelineRequest) GetBranchPattern() string {
	if x != nil {
		return x.BranchPattern
	}
	return ""
}

func (x *CreatePipelineRequest) GetStages() []*PipelineStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *CreatePipelineRequest) GetCiConfig() *CIConfig {
	if x != nil {
		return x.CiConfig
	}
	return nil
}

func (x *CreatePipelineRequest) GetJenkinsJobName() string {
	if x != nil {
		return x.JenkinsJobName
	}
	return ""
}

type CreatePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineResponse) Reset() {
	*x = CreatePipelineResponse{}
	mi := &file_v1_cicd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineResponse) ProtoMessage() {}

func (x *CreatePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineResponse.ProtoReflect.Descriptor instead.
func (*CreatePipelineResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePipelineResponse) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_v1_cicd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{7}
}

func (x *GetPipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineResponse) Reset() {
	*x = GetPipelineResponse{}
	mi := &file_v1_cicd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineResponse) ProtoMessage() {}

func (x *GetPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{8}
}

func (x *GetPipelineResponse) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"` // 선택: 특정 저장소 필터
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_v1_cicd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{9}
}

func (x *ListPipelinesRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListPipelinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipelines     []*Pipeline            `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_v1_cicd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{10}
}

func (x *ListPipelinesResponse) GetPipelines() []*Pipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type DeletePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineRequest) Reset() {
	*x = DeletePipelineRequest{}
	mi := &file_v1_cicd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineRequest) ProtoMessage() {}

func (x *DeletePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineRequest.ProtoReflect.Descriptor instead.
func (*DeletePipelineRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePipelineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineResponse) Reset() {
	*x = DeletePipelineResponse{}
	mi := &file_v1_cicd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineResponse) ProtoMessage() {}

func (x *DeletePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineResponse.ProtoReflect.Descriptor instead.
func (*DeletePipelineResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TriggerBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`                        // 선택: 오버라이드 브랜치
	CommitSha     string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"` // 선택: 특정 커밋
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildRequest) Reset() {
	*x = TriggerBuildRequest{}
	mi := &file_v1_cicd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildRequest) ProtoMessage() {}

func (x *TriggerBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerBuildRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerBuildRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *TriggerBuildRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *TriggerBuildRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

type TriggerBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *Build                 `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildResponse) Reset() {
	*x = TriggerBuildResponse{}
	mi := &file_v1_cicd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildResponse) ProtoMessage() {}

func (x *TriggerBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerBuildResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	BuildNumber   int32                  `protobuf:"varint,2,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_v1_cicd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{15}
}

func (x *GetBuildRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *GetBuildRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

type GetBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *Build                 `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildResponse) Reset() {
	*x = GetBuildResponse{}
	mi := &file_v1_cicd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildResponse) ProtoMessage() {}

func (x *GetBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildResponse.ProtoReflect.Descriptor instead.
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{16}
}

func (x *GetBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

type ListBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 최대 개수 (기본 20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_v1_cicd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{17}
}

func (x *ListBuildsRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ListBuildsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*Build               `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_v1_cicd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{18}
}

func (x *ListBuildsResponse) GetBuilds() []*Build {
	if x != nil {
		return x.Builds
	}
	return nil
}

type GetBuildLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	BuildNumber   int32                  `protobuf:"varint,2,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildLogRequest) Reset() {
	*x = GetBuildLogRequest{}
	mi := &file_v1_cicd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildLogRequest) ProtoMessage() {}

func (x *GetBuildLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildLogRequest.ProtoReflect.Descriptor instead.
func (*GetBuildLogRequest) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{19}
}

func (x *GetBuildLogRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *GetBuildLogRequest) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

type GetBuildLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildLogResponse) Reset() {
	*x = GetBuildLogResponse{}
	mi := &file_v1_cicd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildLogResponse) ProtoMessage() {}

func (x *GetBuildLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cicd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildLogResponse.ProtoReflect.Descriptor instead.
func (*GetBuildLogResponse) Descriptor() ([]byte, []int) {
	return file_v1_cicd_proto_rawDescGZIP(), []int{20}
}

func (x *GetBuildLogResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_v1_cicd_proto protoreflect.FileDescriptor

const file_v1_cicd_proto_rawDesc = "" +
	"\n" +
	"\rv1/cicd.proto\x12\x0egitprovider.v1\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\rJenkinsConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tapi_token\x18\x03 \x01(\tR\bapiToken\"O\n" +
	"\bCIConfig\x129\n" +
	"\ajenkins\x18\x01 \x01(\v2\x1d.gitprovider.v1.JenkinsConfigH\x00R\ajenkinsB\b\n" +
	"\x06config\"f\n" +
	"\rPipelineStage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xcb\x02\n" +
	"\bPipeline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12%\n" +
	"\x0ebranch_pattern\x18\x04 \x01(\tR\rbranchPattern\x125\n" +
	"\x06stages\x18\x05 \x03(\v2\x1d.gitprovider.v1.PipelineStageR\x06stages\x125\n" +
	"\tci_config\x18\x06 \x01(\v2\x18.gitprovider.v1.CIConfigR\bciConfig\x12(\n" +
	"\x10jenkins_job_name\x18\a \x01(\tR\x0ejenkinsJobName\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xde\x02\n" +
	"\x05Build\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\x05R\vbuildNumber\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.gitprovider.v1.BuildStatusR\x06status\x12\x18\n" +
	"\atrigger\x18\x05 \x01(\tR\atrigger\x12\x16\n" +
	"\x06branch\x18\x06 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\a \x01(\tR\tcommitSha\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt\x12)\n" +
	"\x10duration_seconds\x18\n" +
	" \x01(\x05R\x0fdurationSeconds\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\"\x8a\x02\n" +
	"\x15CreatePipelineRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12%\n" +
	"\x0ebranch_pattern\x18\x03 \x01(\tR\rbranchPattern\x125\n" +
	"\x06stages\x18\x04 \x03(\v2\x1d.gitprovider.v1.PipelineStageR\x06stages\x125\n" +
	"\tci_config\x18\x05 \x01(\v2\x18.gitprovider.v1.CIConfigR\bciConfig\x12(\n" +
	"\x10jenkins_job_name\x18\x06 \x01(\tR\x0ejenkinsJobName\"N\n" +
	"\x16CreatePipelineResponse\x124\n" +
	"\bpipeline\x18\x01 \x01(\v2\x18.gitprovider.v1.PipelineR\bpipeline\"$\n" +
	"\x12GetPipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetPipelineResponse\x124\n" +
	"\bpipeline\x18\x01 \x01(\v2\x18.gitprovider.v1.PipelineR\bpipeline\"6\n" +
	"\x14ListPipelinesRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"O\n" +
	"\x15ListPipelinesResponse\x126\n" +
	"\tpipelines\x18\x01 \x03(\v2\x18.gitprovider.v1.PipelineR\tpipelines\"'\n" +
	"\x15DeletePipelineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeletePipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x13TriggerBuildRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\"C\n" +
	"\x14TriggerBuildResponse\x12+\n" +
	"\x05build\x18\x01 \x01(\v2\x15.gitprovider.v1.BuildR\x05build\"U\n" +
	"\x0fGetBuildRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12!\n" +
	"\fbuild_number\x18\x02 \x01(\x05R\vbuildNumber\"?\n" +
	"\x10GetBuildResponse\x12+\n" +
	"\x05build\x18\x01 \x01(\v2\x15.gitprovider.v1.BuildR\x05build\"J\n" +
	"\x11ListBuildsRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x12ListBuildsResponse\x12-\n" +
	"\x06builds\x18\x01 \x03(\v2\x15.gitprovider.v1.BuildR\x06builds\"X\n" +
	"\x12GetBuildLogRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12!\n" +
	"\fbuild_number\x18\x02 \x01(\x05R\vbuildNumber\"'\n" +
	"\x13GetBuildLogResponse\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log*\xac\x01\n" +
	"\vBuildStatus\x12\x1c\n" +
	"\x18BUILD_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BUILD_STATUS_QUEUED\x10\x01\x12\x18\n" +
	"\x14BUILD_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14BUILD_STATUS_SUCCESS\x10\x03\x12\x18\n" +
	"\x14BUILD_STATUS_FAILURE\x10\x04\x12\x18\n" +
	"\x14BUILD_STATUS_ABORTED\x10\x052\xce\a\n" +
	"\vCICDService\x12\x80\x01\n" +
	"\x0eCreatePipeline\x12%.gitprovider.v1.CreatePipelineRequest\x1a&.gitprovider.v1.CreatePipelineResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/pipelines/create\x12t\n" +
	"\vGetPipeline\x12\".gitprovider.v1.GetPipelineRequest\x1a#.gitprovider.v1.GetPipelineResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/pipelines/get\x12{\n" +
	"\rListPipelines\x12$.gitprovider.v1.ListPipelinesRequest\x1a%.gitprovider.v1.ListPipelinesResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/pipelines/list\x12\x80\x01\n" +
	"\x0eDeletePipeline\x12%.gitprovider.v1.DeletePipelineRequest\x1a&.gitprovider.v1.DeletePipelineResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/pipelines/delete\x12x\n" +
	"\fTriggerBuild\x12#.gitprovider.v1.TriggerBuildRequest\x1a$.gitprovider.v1.TriggerBuildResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/builds/trigger\x12h\n" +
	"\bGetBuild\x12\x1f.gitprovider.v1.GetBuildRequest\x1a .gitprovider.v1.GetBuildResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/builds/get\x12o\n" +
	"\n" +
	"ListBuilds\x12!.gitprovider.v1.ListBuildsRequest\x1a\".gitprovider.v1.ListBuildsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/builds/list\x12q\n" +
	"\vGetBuildLog\x12\".gitprovider.v1.GetBuildLogRequest\x1a#.gitprovider.v1.GetBuildLogResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/builds/logB5Z3github.com/runners-high/git-provider/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_v1_cicd_proto_rawDescOnce sync.Once
	file_v1_cicd_proto_rawDescData []byte
)

func file_v1_cicd_proto_rawDescGZIP() []byte {
	file_v1_cicd_proto_rawDescOnce.Do(func() {
		file_v1_cicd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cicd_proto_rawDesc), len(file_v1_cicd_proto_rawDesc)))
	})
	return file_v1_cicd_proto_rawDescData
}

var file_v1_cicd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_cicd_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_cicd_proto_goTypes = []any{
	(BuildStatus)(0),               // 0: gitprovider.v1.BuildStatus
	(*JenkinsConfig)(nil),          // 1: gitprovider.v1.JenkinsConfig
	(*CIConfig)(nil),               // 2: gitprovider.v1.CIConfig
	(*PipelineStage)(nil),          // 3: gitprovider.v1.PipelineStage
	(*Pipeline)(nil),               // 4: gitprovider.v1.Pipeline
	(*Build)(nil),                  // 5: gitprovider.v1.Build
	(*CreatePipelineRequest)(nil),  // 6: gitprovider.v1.CreatePipelineRequest
	(*CreatePipelineResponse)(nil), // 7: gitprovider.v1.CreatePipelineResponse
	(*GetPipelineRequest)(nil),     // 8: gitprovider.v1.GetPipelineRequest
	(*GetPipelineResponse)(nil),    // 9: gitprovider.v1.GetPipelineResponse
	(*ListPipelinesRequest)(nil),   // 10: gitprovider.v1.ListPipelinesRequest
	(*ListPipelinesResponse)(nil),  // 11: gitprovider.v1.ListPipelinesResponse
	(*DeletePipelineRequest)(nil),  // 12: gitprovider.v1.DeletePipelineRequest
	(*DeletePipelineResponse)(nil), // 13: gitprovider.v1.DeletePipelineResponse
	(*TriggerBuildRequest)(nil),    // 14: gitprovider.v1.TriggerBuildRequest
	(*TriggerBuildResponse)(nil),   // 15: gitprovider.v1.TriggerBuildResponse
	(*GetBuildRequest)(nil),        // 16: gitprovider.v1.GetBuildRequest
	(*GetBuildResponse)(nil),       // 17: gitprovider.v1.GetBuildResponse
	(*ListBuildsRequest)(nil),      // 18: gitprovider.v1.ListBuildsRequest
	(*ListBuildsResponse)(nil),     // 19: gitprovider.v1.ListBuildsResponse
	(*GetBuildLogRequest)(nil),     // 20: gitprovider.v1.GetBuildLogRequest
	(*GetBuildLogResponse)(nil),    // 21: gitprovider.v1.GetBuildLogResponse
}
var file_v1_cicd_proto_depIdxs = []int32{
	1,  // 0: gitprovider.v1.CIConfig.jenkins:type_name -> gitprovider.v1.JenkinsConfig
	3,  // 1: gitprovider.v1.Pipeline.stages:type_name -> gitprovider.v1.PipelineStage
	2,  // 2: gitprovider.v1.Pipeline.ci_config:type_name -> gitprovider.v1.CIConfig
	0,  // 3: gitprovider.v1.Build.status:type_name -> gitprovider.v1.BuildStatus
	3,  // 4: gitprovider.v1.CreatePipelineRequest.stages:type_name -> gitprovider.v1.PipelineStage
	2,  // 5: gitprovider.v1.CreatePipelineRequest.ci_config:type_name -> gitprovider.v1.CIConfig
	4,  // 6: gitprovider.v1.CreatePipelineResponse.pipeline:type_name -> gitprovider.v1.Pipeline
	4,  // 7: gitprovider.v1.GetPipelineResponse.pipeline:type_name -> gitprovider.v1.Pipeline
	4,  // 8: gitprovider.v1.ListPipelinesResponse.pipelines:type_name -> gitprovider.v1.Pipeline
	5,  // 9: gitprovider.v1.TriggerBuildResponse.build:type_name -> gitprovider.v1.Build
	5,  // 10: gitprovider.v1.GetBuildResponse.build:type_name -> gitprovider.v1.Build
	5,  // 11: gitprovider.v1.ListBuildsResponse.builds:type_name -> gitprovider.v1.Build
	6,  // 12: gitprovider.v1.CICDService.CreatePipeline:input_type -> gitprovider.v1.CreatePipelineRequest
	8,  // 13: gitprovider.v1.CICDService.GetPipeline:input_type -> gitprovider.v1.GetPipelineRequest
	10, // 14: gitprovider.v1.CICDService.ListPipelines:input_type -> gitprovider.v1.ListPipelinesRequest
	12, // 15: gitprovider.v1.CICDService.DeletePipeline:input_type -> gitprovider.v1.DeletePipelineRequest
	14, // 16: gitprovider.v1.CICDService.TriggerBuild:input_type -> gitprovider.v1.TriggerBuildRequest
	16, // 17: gitprovider.v1.CICDService.GetBuild:input_type -> gitprovider.v1.GetBuildRequest
	18, // 18: gitprovider.v1.CICDService.ListBuilds:input_type -> gitprovider.v1.ListBuildsRequest
	20, // 19: gitprovider.v1.CICDService.GetBuildLog:input_type -> gitprovider.v1.GetBuildLogRequest
	7,  // 20: gitprovider.v1.CICDService.CreatePipeline:output_type -> gitprovider.v1.CreatePipelineResponse
	9,  // 21: gitprovider.v1.CICDService.GetPipeline:output_type -> gitprovider.v1.GetPipelineResponse
	11, // 22: gitprovider.v1.CICDService.ListPipelines:output_type -> gitprovider.v1.ListPipelinesResponse
	13, // 23: gitprovider.v1.CICDService.DeletePipeline:output_type -> gitprovider.v1.DeletePipelineResponse
	15, // 24: gitprovider.v1.CICDService.TriggerBuild:output_type -> gitprovider.v1.TriggerBuildResponse
	17, // 25: gitprovider.v1.CICDService.GetBuild:output_type -> gitprovider.v1.GetBuildResponse
	19, // 26: gitprovider.v1.CICDService.ListBuilds:output_type -> gitprovider.v1.ListBuildsResponse
	21, // 27: gitprovider.v1.CICDService.GetBuildLog:output_type -> gitprovider.v1.GetBuildLogResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_cicd_proto_init() }
func file_v1_cicd_proto_init() {
	if File_v1_cicd_proto != nil {
		return
	}
	file_v1_cicd_proto_msgTypes[1].OneofWrappers = []any{
		(*CIConfig_Jenkins)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cicd_proto_rawDesc), len(file_v1_cicd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_cicd_proto_goTypes,
		DependencyIndexes: file_v1_cicd_proto_depIdxs,
		EnumInfos:         file_v1_cicd_proto_enumTypes,
		MessageInfos:      file_v1_cicd_proto_msgTypes,
	}.Build()
	File_v1_cicd_proto = out.File
	file_v1_cicd_proto_goTypes = nil
	file_v1_cicd_proto_depIdxs = nil
}
