// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: v1/cicd.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CICDService_CreatePipeline_FullMethodName = "/gitprovider.v1.CICDService/CreatePipeline"
	CICDService_GetPipeline_FullMethodName    = "/gitprovider.v1.CICDService/GetPipeline"
	CICDService_ListPipelines_FullMethodName  = "/gitprovider.v1.CICDService/ListPipelines"
	CICDService_DeletePipeline_FullMethodName = "/gitprovider.v1.CICDService/DeletePipeline"
	CICDService_TriggerBuild_FullMethodName   = "/gitprovider.v1.CICDService/TriggerBuild"
	CICDService_GetBuild_FullMethodName       = "/gitprovider.v1.CICDService/GetBuild"
	CICDService_ListBuilds_FullMethodName     = "/gitprovider.v1.CICDService/ListBuilds"
	CICDService_GetBuildLog_FullMethodName    = "/gitprovider.v1.CICDService/GetBuildLog"
)

// CICDServiceClient is the client API for CICDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CICDServiceClient interface {
	CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*CreatePipelineResponse, error)
	GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error)
	ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error)
	DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*DeletePipelineResponse, error)
	TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*TriggerBuildResponse, error)
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error)
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
	GetBuildLog(ctx context.Context, in *GetBuildLogRequest, opts ...grpc.CallOption) (*GetBuildLogResponse, error)
}

type cICDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCICDServiceClient(cc grpc.ClientConnInterface) CICDServiceClient {
	return &cICDServiceClient{cc}
}

func (c *cICDServiceClient) CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*CreatePipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePipelineResponse)
	err := c.cc.Invoke(ctx, CICDService_CreatePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineResponse)
	err := c.cc.Invoke(ctx, CICDService_GetPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPipelinesResponse)
	err := c.cc.Invoke(ctx, CICDService_ListPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*DeletePipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePipelineResponse)
	err := c.cc.Invoke(ctx, CICDService_DeletePipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*TriggerBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerBuildResponse)
	err := c.cc.Invoke(ctx, CICDService_TriggerBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildResponse)
	err := c.cc.Invoke(ctx, CICDService_GetBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuildsResponse)
	err := c.cc.Invoke(ctx, CICDService_ListBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cICDServiceClient) GetBuildLog(ctx context.Context, in *GetBuildLogRequest, opts ...grpc.CallOption) (*GetBuildLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildLogResponse)
	err := c.cc.Invoke(ctx, CICDService_GetBuildLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CICDServiceServer is the server API for CICDService service.
// All implementations must embed UnimplementedCICDServiceServer
// for forward compatibility.
type CICDServiceServer interface {
	CreatePipeline(context.Context, *CreatePipelineRequest) (*CreatePipelineResponse, error)
	GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error)
	ListPipelines(context.Context, *ListPipelinesRequest) (*ListPipelinesResponse, error)
	DeletePipeline(context.Context, *DeletePipelineRequest) (*DeletePipelineResponse, error)
	TriggerBuild(context.Context, *TriggerBuildRequest) (*TriggerBuildResponse, error)
	GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error)
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
	GetBuildLog(context.Context, *GetBuildLogRequest) (*GetBuildLogResponse, error)
	mustEmbedUnimplementedCICDServiceServer()
}

// UnimplementedCICDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCICDServiceServer struct{}

func (UnimplementedCICDServiceServer) CreatePipeline(context.Context, *CreatePipelineRequest) (*CreatePipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePipeline not implemented")
}
func (UnimplementedCICDServiceServer) GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipeline not implemented")
}
func (UnimplementedCICDServiceServer) ListPipelines(context.Context, *ListPipelinesRequest) (*ListPipelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPipelines not implemented")
}
func (UnimplementedCICDServiceServer) DeletePipeline(context.Context, *DeletePipelineRequest) (*DeletePipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePipeline not implemented")
}
func (UnimplementedCICDServiceServer) TriggerBuild(context.Context, *TriggerBuildRequest) (*TriggerBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerBuild not implemented")
}
func (UnimplementedCICDServiceServer) GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuild not implemented")
}
func (UnimplementedCICDServiceServer) ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuilds not implemented")
}
func (UnimplementedCICDServiceServer) GetBuildLog(context.Context, *GetBuildLogRequest) (*GetBuildLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuildLog not implemented")
}
func (UnimplementedCICDServiceServer) mustEmbedUnimplementedCICDServiceServer() {}
func (UnimplementedCICDServiceServer) testEmbeddedByValue()                     {}

// UnsafeCICDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CICDServiceServer will
// result in compilation errors.
type UnsafeCICDServiceServer interface {
	mustEmbedUnimplementedCICDServiceServer()
}

func RegisterCICDServiceServer(s grpc.ServiceRegistrar, srv CICDServiceServer) {
	// If the following call panics, it indicates UnimplementedCICDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CICDService_ServiceDesc, srv)
}

func _CICDService_CreatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).CreatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_CreatePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).CreatePipeline(ctx, req.(*CreatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_GetPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).GetPipeline(ctx, req.(*GetPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_ListPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).ListPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_ListPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).ListPipelines(ctx, req.(*ListPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_DeletePipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).DeletePipeline(ctx, req.(*DeletePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_TriggerBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).TriggerBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_TriggerBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).TriggerBuild(ctx, req.(*TriggerBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_GetBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_ListBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CICDService_GetBuildLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CICDServiceServer).GetBuildLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CICDService_GetBuildLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CICDServiceServer).GetBuildLog(ctx, req.(*GetBuildLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CICDService_ServiceDesc is the grpc.ServiceDesc for CICDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CICDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitprovider.v1.CICDService",
	HandlerType: (*CICDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipeline",
			Handler:    _CICDService_CreatePipeline_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _CICDService_GetPipeline_Handler,
		},
		{
			MethodName: "ListPipelines",
			Handler:    _CICDService_ListPipelines_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _CICDService_DeletePipeline_Handler,
		},
		{
			MethodName: "TriggerBuild",
			Handler:    _CICDService_TriggerBuild_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _CICDService_GetBuild_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _CICDService_ListBuilds_Handler,
		},
		{
			MethodName: "GetBuildLog",
			Handler:    _CICDService_GetBuildLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cicd.proto",
}
