// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: v1/contents.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentsService_GetTree_FullMethodName     = "/gitprovider.v1.ContentsService/GetTree"
	ContentsService_GetContents_FullMethodName = "/gitprovider.v1.ContentsService/GetContents"
	ContentsService_GetReadme_FullMethodName   = "/gitprovider.v1.ContentsService/GetReadme"
)

// ContentsServiceClient is the client API for ContentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentsServiceClient interface {
	// 저장소의 전체 파일 트리를 조회합니다.
	GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeResponse, error)
	// 특정 경로의 파일/디렉토리 내용을 조회합니다.
	GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error)
	// README 파일을 조회합니다.
	GetReadme(ctx context.Context, in *GetReadmeRequest, opts ...grpc.CallOption) (*GetReadmeResponse, error)
}

type contentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentsServiceClient(cc grpc.ClientConnInterface) ContentsServiceClient {
	return &contentsServiceClient{cc}
}

func (c *contentsServiceClient) GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTreeResponse)
	err := c.cc.Invoke(ctx, ContentsService_GetTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentsServiceClient) GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentsResponse)
	err := c.cc.Invoke(ctx, ContentsService_GetContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentsServiceClient) GetReadme(ctx context.Context, in *GetReadmeRequest, opts ...grpc.CallOption) (*GetReadmeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadmeResponse)
	err := c.cc.Invoke(ctx, ContentsService_GetReadme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentsServiceServer is the server API for ContentsService service.
// All implementations must embed UnimplementedContentsServiceServer
// for forward compatibility.
type ContentsServiceServer interface {
	// 저장소의 전체 파일 트리를 조회합니다.
	GetTree(context.Context, *GetTreeRequest) (*GetTreeResponse, error)
	// 특정 경로의 파일/디렉토리 내용을 조회합니다.
	GetContents(context.Context, *GetContentsRequest) (*GetContentsResponse, error)
	// README 파일을 조회합니다.
	GetReadme(context.Context, *GetReadmeRequest) (*GetReadmeResponse, error)
	mustEmbedUnimplementedContentsServiceServer()
}

// UnimplementedContentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentsServiceServer struct{}

func (UnimplementedContentsServiceServer) GetTree(context.Context, *GetTreeRequest) (*GetTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedContentsServiceServer) GetContents(context.Context, *GetContentsRequest) (*GetContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContents not implemented")
}
func (UnimplementedContentsServiceServer) GetReadme(context.Context, *GetReadmeRequest) (*GetReadmeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadme not implemented")
}
func (UnimplementedContentsServiceServer) mustEmbedUnimplementedContentsServiceServer() {}
func (UnimplementedContentsServiceServer) testEmbeddedByValue()                         {}

// UnsafeContentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentsServiceServer will
// result in compilation errors.
type UnsafeContentsServiceServer interface {
	mustEmbedUnimplementedContentsServiceServer()
}

func RegisterContentsServiceServer(s grpc.ServiceRegistrar, srv ContentsServiceServer) {
	// If the following call panics, it indicates UnimplementedContentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentsService_ServiceDesc, srv)
}

func _ContentsService_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentsServiceServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentsService_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentsServiceServer).GetTree(ctx, req.(*GetTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentsService_GetContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentsServiceServer).GetContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentsService_GetContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentsServiceServer).GetContents(ctx, req.(*GetContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentsService_GetReadme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadmeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentsServiceServer).GetReadme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentsService_GetReadme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentsServiceServer).GetReadme(ctx, req.(*GetReadmeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentsService_ServiceDesc is the grpc.ServiceDesc for ContentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitprovider.v1.ContentsService",
	HandlerType: (*ContentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTree",
			Handler:    _ContentsService_GetTree_Handler,
		},
		{
			MethodName: "GetContents",
			Handler:    _ContentsService_GetContents_Handler,
		},
		{
			MethodName: "GetReadme",
			Handler:    _ContentsService_GetReadme_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/contents.proto",
}
