// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: v1/mergerequest.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MergeRequestState는 MR/PR의 상태를 나타냅니다.
type MergeRequestState int32

const (
	MergeRequestState_MERGE_REQUEST_STATE_UNSPECIFIED MergeRequestState = 0
	MergeRequestState_MERGE_REQUEST_STATE_OPEN        MergeRequestState = 1 // 열림
	MergeRequestState_MERGE_REQUEST_STATE_CLOSED      MergeRequestState = 2 // 닫힘 (머지 없이)
	MergeRequestState_MERGE_REQUEST_STATE_MERGED      MergeRequestState = 3 // 머지됨
	MergeRequestState_MERGE_REQUEST_STATE_DRAFT       MergeRequestState = 4 // 초안
)

// Enum value maps for MergeRequestState.
var (
	MergeRequestState_name = map[int32]string{
		0: "MERGE_REQUEST_STATE_UNSPECIFIED",
		1: "MERGE_REQUEST_STATE_OPEN",
		2: "MERGE_REQUEST_STATE_CLOSED",
		3: "MERGE_REQUEST_STATE_MERGED",
		4: "MERGE_REQUEST_STATE_DRAFT",
	}
	MergeRequestState_value = map[string]int32{
		"MERGE_REQUEST_STATE_UNSPECIFIED": 0,
		"MERGE_REQUEST_STATE_OPEN":        1,
		"MERGE_REQUEST_STATE_CLOSED":      2,
		"MERGE_REQUEST_STATE_MERGED":      3,
		"MERGE_REQUEST_STATE_DRAFT":       4,
	}
)

func (x MergeRequestState) Enum() *MergeRequestState {
	p := new(MergeRequestState)
	*p = x
	return p
}

func (x MergeRequestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeRequestState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_mergerequest_proto_enumTypes[0].Descriptor()
}

func (MergeRequestState) Type() protoreflect.EnumType {
	return &file_v1_mergerequest_proto_enumTypes[0]
}

func (x MergeRequestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeRequestState.Descriptor instead.
func (MergeRequestState) EnumDescriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{0}
}

// ReviewState는 리뷰 상태를 나타냅니다.
type ReviewState int32

const (
	ReviewState_REVIEW_STATE_UNSPECIFIED       ReviewState = 0
	ReviewState_REVIEW_STATE_PENDING           ReviewState = 1 // 리뷰 대기
	ReviewState_REVIEW_STATE_APPROVED          ReviewState = 2 // 승인됨
	ReviewState_REVIEW_STATE_CHANGES_REQUESTED ReviewState = 3 // 변경 요청
	ReviewState_REVIEW_STATE_COMMENTED         ReviewState = 4 // 의견만
	ReviewState_REVIEW_STATE_DISMISSED         ReviewState = 5 // 기각됨
)

// Enum value maps for ReviewState.
var (
	ReviewState_name = map[int32]string{
		0: "REVIEW_STATE_UNSPECIFIED",
		1: "REVIEW_STATE_PENDING",
		2: "REVIEW_STATE_APPROVED",
		3: "REVIEW_STATE_CHANGES_REQUESTED",
		4: "REVIEW_STATE_COMMENTED",
		5: "REVIEW_STATE_DISMISSED",
	}
	ReviewState_value = map[string]int32{
		"REVIEW_STATE_UNSPECIFIED":       0,
		"REVIEW_STATE_PENDING":           1,
		"REVIEW_STATE_APPROVED":          2,
		"REVIEW_STATE_CHANGES_REQUESTED": 3,
		"REVIEW_STATE_COMMENTED":         4,
		"REVIEW_STATE_DISMISSED":         5,
	}
)

func (x ReviewState) Enum() *ReviewState {
	p := new(ReviewState)
	*p = x
	return p
}

func (x ReviewState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_mergerequest_proto_enumTypes[1].Descriptor()
}

func (ReviewState) Type() protoreflect.EnumType {
	return &file_v1_mergerequest_proto_enumTypes[1]
}

func (x ReviewState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewState.Descriptor instead.
func (ReviewState) EnumDescriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{1}
}

// MergeMethod는 머지 방법을 나타냅니다.
type MergeMethod int32

const (
	MergeMethod_MERGE_METHOD_UNSPECIFIED MergeMethod = 0
	MergeMethod_MERGE_METHOD_MERGE       MergeMethod = 1 // 일반 머지 커밋
	MergeMethod_MERGE_METHOD_SQUASH      MergeMethod = 2 // 스쿼시 머지
	MergeMethod_MERGE_METHOD_REBASE      MergeMethod = 3 // 리베이스 머지
)

// Enum value maps for MergeMethod.
var (
	MergeMethod_name = map[int32]string{
		0: "MERGE_METHOD_UNSPECIFIED",
		1: "MERGE_METHOD_MERGE",
		2: "MERGE_METHOD_SQUASH",
		3: "MERGE_METHOD_REBASE",
	}
	MergeMethod_value = map[string]int32{
		"MERGE_METHOD_UNSPECIFIED": 0,
		"MERGE_METHOD_MERGE":       1,
		"MERGE_METHOD_SQUASH":      2,
		"MERGE_METHOD_REBASE":      3,
	}
)

func (x MergeMethod) Enum() *MergeMethod {
	p := new(MergeMethod)
	*p = x
	return p
}

func (x MergeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_mergerequest_proto_enumTypes[2].Descriptor()
}

func (MergeMethod) Type() protoreflect.EnumType {
	return &file_v1_mergerequest_proto_enumTypes[2]
}

func (x MergeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeMethod.Descriptor instead.
func (MergeMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{2}
}

// MergeRequest는 PR/MR 정보입니다.
type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // Provider의 MR ID
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`                                     // MR 번호
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                        // 제목
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                            // 설명
	State         MergeRequestState      `protobuf:"varint,5,opt,name=state,proto3,enum=gitprovider.v1.MergeRequestState" json:"state,omitempty"` // 상태
	SourceBranch  string                 `protobuf:"bytes,6,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`      // 소스 브랜치
	TargetBranch  string                 `protobuf:"bytes,7,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`      // 타겟 브랜치
	Author        *User                  `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`                                      // 작성자
	Assignees     []*User                `protobuf:"bytes,9,rep,name=assignees,proto3" json:"assignees,omitempty"`                                // 담당자
	Reviewers     []*User                `protobuf:"bytes,10,rep,name=reviewers,proto3" json:"reviewers,omitempty"`                               // 리뷰어
	Labels        []string               `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`                                     // 라벨
	Url           string                 `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`                                           // Provider URL
	Draft         bool                   `protobuf:"varint,13,opt,name=draft,proto3" json:"draft,omitempty"`                                      // 초안 여부
	Mergeable     bool                   `protobuf:"varint,14,opt,name=mergeable,proto3" json:"mergeable,omitempty"`                              // 머지 가능 여부
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // 생성 시간
	UpdatedAt     string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 수정 시간
	MergedAt      string                 `protobuf:"bytes,17,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`                 // 머지 시간
	ClosedAt      string                 `protobuf:"bytes,18,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`                 // 닫힌 시간
	MergedBy      *User                  `protobuf:"bytes,19,opt,name=merged_by,json=mergedBy,proto3" json:"merged_by,omitempty"`                 // 머지한 사람
	HeadSha       string                 `protobuf:"bytes,20,opt,name=head_sha,json=headSha,proto3" json:"head_sha,omitempty"`                    // 소스 브랜치의 최신 SHA
	BaseSha       string                 `protobuf:"bytes,21,opt,name=base_sha,json=baseSha,proto3" json:"base_sha,omitempty"`                    // 타겟 브랜치의 SHA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{0}
}

func (x *MergeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MergeRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MergeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MergeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MergeRequest) GetState() MergeRequestState {
	if x != nil {
		return x.State
	}
	return MergeRequestState_MERGE_REQUEST_STATE_UNSPECIFIED
}

func (x *MergeRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *MergeRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *MergeRequest) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *MergeRequest) GetAssignees() []*User {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *MergeRequest) GetReviewers() []*User {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

func (x *MergeRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MergeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MergeRequest) GetDraft() bool {
	if x != nil {
		return x.Draft
	}
	return false
}

func (x *MergeRequest) GetMergeable() bool {
	if x != nil {
		return x.Mergeable
	}
	return false
}

func (x *MergeRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MergeRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MergeRequest) GetMergedAt() string {
	if x != nil {
		return x.MergedAt
	}
	return ""
}

func (x *MergeRequest) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *MergeRequest) GetMergedBy() *User {
	if x != nil {
		return x.MergedBy
	}
	return nil
}

func (x *MergeRequest) GetHeadSha() string {
	if x != nil {
		return x.HeadSha
	}
	return ""
}

func (x *MergeRequest) GetBaseSha() string {
	if x != nil {
		return x.BaseSha
	}
	return ""
}

// User는 사용자 정보입니다.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // 사용자 ID
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`                          // 로그인명
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // 표시 이름
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                          // 이메일
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 아바타 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_mergerequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// MergeRequestDiff는 MR의 변경사항입니다.
type MergeRequestDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileDiff            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`                                    // 변경된 파일 목록
	Additions     int32                  `protobuf:"varint,2,opt,name=additions,proto3" json:"additions,omitempty"`                           // 추가된 라인 수
	Deletions     int32                  `protobuf:"varint,3,opt,name=deletions,proto3" json:"deletions,omitempty"`                           // 삭제된 라인 수
	ChangedFiles  int32                  `protobuf:"varint,4,opt,name=changed_files,json=changedFiles,proto3" json:"changed_files,omitempty"` // 변경된 파일 수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequestDiff) Reset() {
	*x = MergeRequestDiff{}
	mi := &file_v1_mergerequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequestDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequestDiff) ProtoMessage() {}

func (x *MergeRequestDiff) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequestDiff.ProtoReflect.Descriptor instead.
func (*MergeRequestDiff) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{2}
}

func (x *MergeRequestDiff) GetFiles() []*FileDiff {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MergeRequestDiff) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *MergeRequestDiff) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

func (x *MergeRequestDiff) GetChangedFiles() int32 {
	if x != nil {
		return x.ChangedFiles
	}
	return 0
}

// FileDiff는 파일별 변경사항입니다.
type FileDiff struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Filename         string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                                         // 파일 경로
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                             // 상태 (added, removed, modified, renamed)
	Additions        int32                  `protobuf:"varint,3,opt,name=additions,proto3" json:"additions,omitempty"`                                      // 추가된 라인
	Deletions        int32                  `protobuf:"varint,4,opt,name=deletions,proto3" json:"deletions,omitempty"`                                      // 삭제된 라인
	Patch            string                 `protobuf:"bytes,5,opt,name=patch,proto3" json:"patch,omitempty"`                                               // diff 패치 내용
	PreviousFilename string                 `protobuf:"bytes,6,opt,name=previous_filename,json=previousFilename,proto3" json:"previous_filename,omitempty"` // 이전 파일명 (rename의 경우)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileDiff) Reset() {
	*x = FileDiff{}
	mi := &file_v1_mergerequest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiff) ProtoMessage() {}

func (x *FileDiff) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiff.ProtoReflect.Descriptor instead.
func (*FileDiff) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{3}
}

func (x *FileDiff) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileDiff) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileDiff) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *FileDiff) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

func (x *FileDiff) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *FileDiff) GetPreviousFilename() string {
	if x != nil {
		return x.PreviousFilename
	}
	return ""
}

// Review는 리뷰 정보입니다.
type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 리뷰 ID
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`                                    // 리뷰어
	State         ReviewState            `protobuf:"varint,3,opt,name=state,proto3,enum=gitprovider.v1.ReviewState" json:"state,omitempty"` // 리뷰 상태
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                    // 리뷰 본문
	SubmittedAt   string                 `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`   // 제출 시간
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_v1_mergerequest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{4}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Review) GetState() ReviewState {
	if x != nil {
		return x.State
	}
	return ReviewState_REVIEW_STATE_UNSPECIFIED
}

func (x *Review) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Review) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

// Comment는 댓글 정보입니다.
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 댓글 ID
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`                                      // 작성자
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                      // 댓글 내용
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                      // 파일 경로 (라인 코멘트인 경우)
	Line          int32                  `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`                                     // 라인 번호 (라인 코멘트인 경우)
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 생성 시간
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 수정 시간
	InReplyToId   string                 `protobuf:"bytes,8,opt,name=in_reply_to_id,json=inReplyToId,proto3" json:"in_reply_to_id,omitempty"` // 답글 대상 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_v1_mergerequest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Comment) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Comment) GetInReplyToId() string {
	if x != nil {
		return x.InReplyToId
	}
	return ""
}

// MR 목록 조회 요청
type ListMergeRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                                // 저장소 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`                              // 저장소 이름
	State         MergeRequestState      `protobuf:"varint,4,opt,name=state,proto3,enum=gitprovider.v1.MergeRequestState" json:"state,omitempty"` // 필터: 상태
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`                                      // 필터: 작성자
	Assignee      string                 `protobuf:"bytes,6,opt,name=assignee,proto3" json:"assignee,omitempty"`                                  // 필터: 담당자
	Labels        string                 `protobuf:"bytes,7,opt,name=labels,proto3" json:"labels,omitempty"`                                      // 필터: 라벨 (콤마 구분)
	Base          string                 `protobuf:"bytes,8,opt,name=base,proto3" json:"base,omitempty"`                                          // 필터: 타겟 브랜치
	Head          string                 `protobuf:"bytes,9,opt,name=head,proto3" json:"head,omitempty"`                                          // 필터: 소스 브랜치
	Page          int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,11,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMergeRequestsRequest) Reset() {
	*x = ListMergeRequestsRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMergeRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMergeRequestsRequest) ProtoMessage() {}

func (x *ListMergeRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMergeRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListMergeRequestsRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{6}
}

func (x *ListMergeRequestsRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ListMergeRequestsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetState() MergeRequestState {
	if x != nil {
		return x.State
	}
	return MergeRequestState_MERGE_REQUEST_STATE_UNSPECIFIED
}

func (x *ListMergeRequestsRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ListMergeRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMergeRequestsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListMergeRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MergeRequests []*MergeRequest        `protobuf:"bytes,1,rep,name=merge_requests,json=mergeRequests,proto3" json:"merge_requests,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMergeRequestsResponse) Reset() {
	*x = ListMergeRequestsResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMergeRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMergeRequestsResponse) ProtoMessage() {}

func (x *ListMergeRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMergeRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListMergeRequestsResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{7}
}

func (x *ListMergeRequestsResponse) GetMergeRequests() []*MergeRequest {
	if x != nil {
		return x.MergeRequests
	}
	return nil
}

func (x *ListMergeRequestsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// MR 상세 조회 요청
type GetMergeRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"` // MR 번호
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMergeRequestRequest) Reset() {
	*x = GetMergeRequestRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeRequestRequest) ProtoMessage() {}

func (x *GetMergeRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeRequestRequest.ProtoReflect.Descriptor instead.
func (*GetMergeRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{8}
}

func (x *GetMergeRequestRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetMergeRequestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMergeRequestRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetMergeRequestRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetMergeRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MergeRequest  *MergeRequest          `protobuf:"bytes,1,opt,name=merge_request,json=mergeRequest,proto3" json:"merge_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMergeRequestResponse) Reset() {
	*x = GetMergeRequestResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeRequestResponse) ProtoMessage() {}

func (x *GetMergeRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeRequestResponse.ProtoReflect.Descriptor instead.
func (*GetMergeRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{9}
}

func (x *GetMergeRequestResponse) GetMergeRequest() *MergeRequest {
	if x != nil {
		return x.MergeRequest
	}
	return nil
}

// MR 생성 요청
type CreateMergeRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                   // 제목
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                       // 설명
	SourceBranch  string                 `protobuf:"bytes,6,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"` // 소스 브랜치
	TargetBranch  string                 `protobuf:"bytes,7,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"` // 타겟 브랜치
	Draft         bool                   `protobuf:"varint,8,opt,name=draft,proto3" json:"draft,omitempty"`                                  // 초안 여부
	Assignees     []string               `protobuf:"bytes,9,rep,name=assignees,proto3" json:"assignees,omitempty"`                           // 담당자 로그인명
	Reviewers     []string               `protobuf:"bytes,10,rep,name=reviewers,proto3" json:"reviewers,omitempty"`                          // 리뷰어 로그인명
	Labels        []string               `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`                                // 라벨
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMergeRequestRequest) Reset() {
	*x = CreateMergeRequestRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMergeRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMergeRequestRequest) ProtoMessage() {}

func (x *CreateMergeRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMergeRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateMergeRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMergeRequestRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *CreateMergeRequestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *CreateMergeRequestRequest) GetDraft() bool {
	if x != nil {
		return x.Draft
	}
	return false
}

func (x *CreateMergeRequestRequest) GetAssignees() []string {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *CreateMergeRequestRequest) GetReviewers() []string {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

func (x *CreateMergeRequestRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateMergeRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MergeRequest  *MergeRequest          `protobuf:"bytes,1,opt,name=merge_request,json=mergeRequest,proto3" json:"merge_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMergeRequestResponse) Reset() {
	*x = CreateMergeRequestResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMergeRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMergeRequestResponse) ProtoMessage() {}

func (x *CreateMergeRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMergeRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateMergeRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMergeRequestResponse) GetMergeRequest() *MergeRequest {
	if x != nil {
		return x.MergeRequest
	}
	return nil
}

// MR 수정 요청
type UpdateMergeRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	State         MergeRequestState      `protobuf:"varint,7,opt,name=state,proto3,enum=gitprovider.v1.MergeRequestState" json:"state,omitempty"` // 상태 변경 (OPEN, CLOSED)
	TargetBranch  string                 `protobuf:"bytes,8,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`      // 타겟 브랜치 변경
	Assignees     []string               `protobuf:"bytes,9,rep,name=assignees,proto3" json:"assignees,omitempty"`
	Reviewers     []string               `protobuf:"bytes,10,rep,name=reviewers,proto3" json:"reviewers,omitempty"`
	Labels        []string               `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMergeRequestRequest) Reset() {
	*x = UpdateMergeRequestRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMergeRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMergeRequestRequest) ProtoMessage() {}

func (x *UpdateMergeRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMergeRequestRequest.ProtoReflect.Descriptor instead.
func (*UpdateMergeRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMergeRequestRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *UpdateMergeRequestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateMergeRequestRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpdateMergeRequestRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *UpdateMergeRequestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMergeRequestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMergeRequestRequest) GetState() MergeRequestState {
	if x != nil {
		return x.State
	}
	return MergeRequestState_MERGE_REQUEST_STATE_UNSPECIFIED
}

func (x *UpdateMergeRequestRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *UpdateMergeRequestRequest) GetAssignees() []string {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *UpdateMergeRequestRequest) GetReviewers() []string {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

func (x *UpdateMergeRequestRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateMergeRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MergeRequest  *MergeRequest          `protobuf:"bytes,1,opt,name=merge_request,json=mergeRequest,proto3" json:"merge_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMergeRequestResponse) Reset() {
	*x = UpdateMergeRequestResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMergeRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMergeRequestResponse) ProtoMessage() {}

func (x *UpdateMergeRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMergeRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateMergeRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMergeRequestResponse) GetMergeRequest() *MergeRequest {
	if x != nil {
		return x.MergeRequest
	}
	return nil
}

// MR 머지 요청
type MergeMergeRequestRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace          string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository         string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number             int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	CommitTitle        string                 `protobuf:"bytes,5,opt,name=commit_title,json=commitTitle,proto3" json:"commit_title,omitempty"`                                  // 커밋 제목 (선택)
	CommitMessage      string                 `protobuf:"bytes,6,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`                            // 커밋 메시지 (선택)
	MergeMethod        MergeMethod            `protobuf:"varint,7,opt,name=merge_method,json=mergeMethod,proto3,enum=gitprovider.v1.MergeMethod" json:"merge_method,omitempty"` // 머지 방법
	DeleteSourceBranch bool                   `protobuf:"varint,8,opt,name=delete_source_branch,json=deleteSourceBranch,proto3" json:"delete_source_branch,omitempty"`          // 소스 브랜치 삭제 여부
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MergeMergeRequestRequest) Reset() {
	*x = MergeMergeRequestRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeMergeRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeMergeRequestRequest) ProtoMessage() {}

func (x *MergeMergeRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeMergeRequestRequest.ProtoReflect.Descriptor instead.
func (*MergeMergeRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{14}
}

func (x *MergeMergeRequestRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *MergeMergeRequestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MergeMergeRequestRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *MergeMergeRequestRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MergeMergeRequestRequest) GetCommitTitle() string {
	if x != nil {
		return x.CommitTitle
	}
	return ""
}

func (x *MergeMergeRequestRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *MergeMergeRequestRequest) GetMergeMethod() MergeMethod {
	if x != nil {
		return x.MergeMethod
	}
	return MergeMethod_MERGE_METHOD_UNSPECIFIED
}

func (x *MergeMergeRequestRequest) GetDeleteSourceBranch() bool {
	if x != nil {
		return x.DeleteSourceBranch
	}
	return false
}

type MergeMergeRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MergeRequest  *MergeRequest          `protobuf:"bytes,1,opt,name=merge_request,json=mergeRequest,proto3" json:"merge_request,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"` // 머지 커밋 SHA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeMergeRequestResponse) Reset() {
	*x = MergeMergeRequestResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeMergeRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeMergeRequestResponse) ProtoMessage() {}

func (x *MergeMergeRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeMergeRequestResponse.ProtoReflect.Descriptor instead.
func (*MergeMergeRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{15}
}

func (x *MergeMergeRequestResponse) GetMergeRequest() *MergeRequest {
	if x != nil {
		return x.MergeRequest
	}
	return nil
}

func (x *MergeMergeRequestResponse) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

// MR Diff 조회 요청
type GetMergeRequestDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMergeRequestDiffRequest) Reset() {
	*x = GetMergeRequestDiffRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeRequestDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeRequestDiffRequest) ProtoMessage() {}

func (x *GetMergeRequestDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeRequestDiffRequest.ProtoReflect.Descriptor instead.
func (*GetMergeRequestDiffRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{16}
}

func (x *GetMergeRequestDiffRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetMergeRequestDiffRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMergeRequestDiffRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetMergeRequestDiffRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetMergeRequestDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          *MergeRequestDiff      `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMergeRequestDiffResponse) Reset() {
	*x = GetMergeRequestDiffResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeRequestDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeRequestDiffResponse) ProtoMessage() {}

func (x *GetMergeRequestDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeRequestDiffResponse.ProtoReflect.Descriptor instead.
func (*GetMergeRequestDiffResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{17}
}

func (x *GetMergeRequestDiffResponse) GetDiff() *MergeRequestDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

// 리뷰 목록 조회
type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{18}
}

func (x *ListReviewsRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ListReviewsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListReviewsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListReviewsRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{19}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// 리뷰 제출
type SubmitReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	State         ReviewState            `protobuf:"varint,5,opt,name=state,proto3,enum=gitprovider.v1.ReviewState" json:"state,omitempty"` // APPROVED, CHANGES_REQUESTED, COMMENTED
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                                    // 리뷰 본문
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{20}
}

func (x *SubmitReviewRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *SubmitReviewRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubmitReviewRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SubmitReviewRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *SubmitReviewRequest) GetState() ReviewState {
	if x != nil {
		return x.State
	}
	return ReviewState_REVIEW_STATE_UNSPECIFIED
}

func (x *SubmitReviewRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SubmitReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewResponse) Reset() {
	*x = SubmitReviewResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewResponse) ProtoMessage() {}

func (x *SubmitReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitReviewResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{21}
}

func (x *SubmitReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

// 댓글 목록 조회
type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{22}
}

func (x *ListCommentsRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ListCommentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListCommentsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListCommentsRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{23}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// 댓글 생성
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                              // 댓글 내용
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                              // 파일 경로 (라인 코멘트)
	Line          int32                  `protobuf:"varint,7,opt,name=line,proto3" json:"line,omitempty"`                             // 라인 번호 (라인 코멘트)
	CommitId      string                 `protobuf:"bytes,8,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`      // 커밋 ID (라인 코멘트)
	InReplyTo     string                 `protobuf:"bytes,9,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"` // 답글 대상 댓글 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{24}
}

func (x *CreateCommentRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *CreateCommentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateCommentRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CreateCommentRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateCommentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateCommentRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CreateCommentRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CreateCommentRequest) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{25}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// 댓글 수정
type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"` // MR/PR 번호
	CommentId     string                 `protobuf:"bytes,5,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateCommentRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *UpdateCommentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateCommentRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpdateCommentRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *UpdateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// 댓글 삭제
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"` // MR/PR 번호
	CommentId     string                 `protobuf:"bytes,5,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_v1_mergerequest_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteCommentRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *DeleteCommentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteCommentRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DeleteCommentRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_v1_mergerequest_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mergerequest_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_v1_mergerequest_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_mergerequest_proto protoreflect.FileDescriptor

const file_v1_mergerequest_proto_rawDesc = "" +
	"\n" +
	"\x15v1/mergerequest.proto\x12\x0egitprovider.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x11v1/provider.proto\"\xc6\x05\n" +
	"\fMergeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\x05state\x18\x05 \x01(\x0e2!.gitprovider.v1.MergeRequestStateR\x05state\x12#\n" +
	"\rsource_branch\x18\x06 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\a \x01(\tR\ftargetBranch\x12,\n" +
	"\x06author\x18\b \x01(\v2\x14.gitprovider.v1.UserR\x06author\x122\n" +
	"\tassignees\x18\t \x03(\v2\x14.gitprovider.v1.UserR\tassignees\x122\n" +
	"\treviewers\x18\n" +
	" \x03(\v2\x14.gitprovider.v1.UserR\treviewers\x12\x16\n" +
	"\x06labels\x18\v \x03(\tR\x06labels\x12\x10\n" +
	"\x03url\x18\f \x01(\tR\x03url\x12\x14\n" +
	"\x05draft\x18\r \x01(\bR\x05draft\x12\x1c\n" +
	"\tmergeable\x18\x0e \x01(\bR\tmergeable\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tmerged_at\x18\x11 \x01(\tR\bmergedAt\x12\x1b\n" +
	"\tclosed_at\x18\x12 \x01(\tR\bclosedAt\x121\n" +
	"\tmerged_by\x18\x13 \x01(\v2\x14.gitprovider.v1.UserR\bmergedBy\x12\x19\n" +
	"\bhead_sha\x18\x14 \x01(\tR\aheadSha\x12\x19\n" +
	"\bbase_sha\x18\x15 \x01(\tR\abaseSha\"u\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"\xa3\x01\n" +
	"\x10MergeRequestDiff\x12.\n" +
	"\x05files\x18\x01 \x03(\v2\x18.gitprovider.v1.FileDiffR\x05files\x12\x1c\n" +
	"\tadditions\x18\x02 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x03 \x01(\x05R\tdeletions\x12#\n" +
	"\rchanged_files\x18\x04 \x01(\x05R\fchangedFiles\"\xbd\x01\n" +
	"\bFileDiff\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tadditions\x18\x03 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x04 \x01(\x05R\tdeletions\x12\x14\n" +
	"\x05patch\x18\x05 \x01(\tR\x05patch\x12+\n" +
	"\x11previous_filename\x18\x06 \x01(\tR\x10previousFilename\"\xac\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.gitprovider.v1.UserR\x04user\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.gitprovider.v1.ReviewStateR\x05state\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12!\n" +
	"\fsubmitted_at\x18\x05 \x01(\tR\vsubmittedAt\"\xe2\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.gitprovider.v1.UserR\x04user\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x05 \x01(\x05R\x04line\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12#\n" +
	"\x0ein_reply_to_id\x18\b \x01(\tR\vinReplyToId\"\xf0\x02\n" +
	"\x18ListMergeRequestsRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2!.gitprovider.v1.MergeRequestStateR\x05state\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1a\n" +
	"\bassignee\x18\x06 \x01(\tR\bassignee\x12\x16\n" +
	"\x06labels\x18\a \x01(\tR\x06labels\x12\x12\n" +
	"\x04base\x18\b \x01(\tR\x04base\x12\x12\n" +
	"\x04head\x18\t \x01(\tR\x04head\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\v \x01(\x05R\aperPage\"\x81\x01\n" +
	"\x19ListMergeRequestsResponse\x12C\n" +
	"\x0emerge_requests\x18\x01 \x03(\v2\x1c.gitprovider.v1.MergeRequestR\rmergeRequests\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xaa\x01\n" +
	"\x16GetMergeRequestRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\"\\\n" +
	"\x17GetMergeRequestResponse\x12A\n" +
	"\rmerge_request\x18\x01 \x01(\v2\x1c.gitprovider.v1.MergeRequestR\fmergeRequest\"\x81\x03\n" +
	"\x19CreateMergeRequestRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rsource_branch\x18\x06 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\a \x01(\tR\ftargetBranch\x12\x14\n" +
	"\x05draft\x18\b \x01(\bR\x05draft\x12\x1c\n" +
	"\tassignees\x18\t \x03(\tR\tassignees\x12\x1c\n" +
	"\treviewers\x18\n" +
	" \x03(\tR\treviewers\x12\x16\n" +
	"\x06labels\x18\v \x03(\tR\x06labels\"_\n" +
	"\x1aCreateMergeRequestResponse\x12A\n" +
	"\rmerge_request\x18\x01 \x01(\v2\x1c.gitprovider.v1.MergeRequestR\fmergeRequest\"\x97\x03\n" +
	"\x19UpdateMergeRequestRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x127\n" +
	"\x05state\x18\a \x01(\x0e2!.gitprovider.v1.MergeRequestStateR\x05state\x12#\n" +
	"\rtarget_branch\x18\b \x01(\tR\ftargetBranch\x12\x1c\n" +
	"\tassignees\x18\t \x03(\tR\tassignees\x12\x1c\n" +
	"\treviewers\x18\n" +
	" \x03(\tR\treviewers\x12\x16\n" +
	"\x06labels\x18\v \x03(\tR\x06labels\"_\n" +
	"\x1aUpdateMergeRequestResponse\x12A\n" +
	"\rmerge_request\x18\x01 \x01(\v2\x1c.gitprovider.v1.MergeRequestR\fmergeRequest\"\xe8\x02\n" +
	"\x18MergeMergeRequestRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12!\n" +
	"\fcommit_title\x18\x05 \x01(\tR\vcommitTitle\x12%\n" +
	"\x0ecommit_message\x18\x06 \x01(\tR\rcommitMessage\x12>\n" +
	"\fmerge_method\x18\a \x01(\x0e2\x1b.gitprovider.v1.MergeMethodR\vmergeMethod\x120\n" +
	"\x14delete_source_branch\x18\b \x01(\bR\x12deleteSourceBranch\"p\n" +
	"\x19MergeMergeRequestResponse\x12A\n" +
	"\rmerge_request\x18\x01 \x01(\v2\x1c.gitprovider.v1.MergeRequestR\fmergeRequest\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\"\xae\x01\n" +
	"\x1aGetMergeRequestDiffRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\"S\n" +
	"\x1bGetMergeRequestDiffResponse\x124\n" +
	"\x04diff\x18\x01 \x01(\v2 .gitprovider.v1.MergeRequestDiffR\x04diff\"\xa6\x01\n" +
	"\x12ListReviewsRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\"G\n" +
	"\x13ListReviewsResponse\x120\n" +
	"\areviews\x18\x01 \x03(\v2\x16.gitprovider.v1.ReviewR\areviews\"\xee\x01\n" +
	"\x13SubmitReviewRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x121\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1b.gitprovider.v1.ReviewStateR\x05state\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"F\n" +
	"\x14SubmitReviewResponse\x12.\n" +
	"\x06review\x18\x01 \x01(\v2\x16.gitprovider.v1.ReviewR\x06review\"\xa7\x01\n" +
	"\x13ListCommentsRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\"K\n" +
	"\x14ListCommentsResponse\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.gitprovider.v1.CommentR\bcomments\"\xa1\x02\n" +
	"\x14CreateCommentRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\a \x01(\x05R\x04line\x12\x1b\n" +
	"\tcommit_id\x18\b \x01(\tR\bcommitId\x12\x1e\n" +
	"\vin_reply_to\x18\t \x01(\tR\tinReplyTo\"J\n" +
	"\x15CreateCommentResponse\x121\n" +
	"\acomment\x18\x01 \x01(\v2\x17.gitprovider.v1.CommentR\acomment\"\xdb\x01\n" +
	"\x14UpdateCommentRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x05 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\"J\n" +
	"\x15UpdateCommentResponse\x121\n" +
	"\acomment\x18\x01 \x01(\v2\x17.gitprovider.v1.CommentR\acomment\"\xc7\x01\n" +
	"\x14DeleteCommentRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x05 \x01(\tR\tcommentId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xb5\x01\n" +
	"\x11MergeRequestState\x12#\n" +
	"\x1fMERGE_REQUEST_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MERGE_REQUEST_STATE_OPEN\x10\x01\x12\x1e\n" +
	"\x1aMERGE_REQUEST_STATE_CLOSED\x10\x02\x12\x1e\n" +
	"\x1aMERGE_REQUEST_STATE_MERGED\x10\x03\x12\x1d\n" +
	"\x19MERGE_REQUEST_STATE_DRAFT\x10\x04*\xbc\x01\n" +
	"\vReviewState\x12\x1c\n" +
	"\x18REVIEW_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REVIEW_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15REVIEW_STATE_APPROVED\x10\x02\x12\"\n" +
	"\x1eREVIEW_STATE_CHANGES_REQUESTED\x10\x03\x12\x1a\n" +
	"\x16REVIEW_STATE_COMMENTED\x10\x04\x12\x1a\n" +
	"\x16REVIEW_STATE_DISMISSED\x10\x05*u\n" +
	"\vMergeMethod\x12\x1c\n" +
	"\x18MERGE_METHOD_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MERGE_METHOD_MERGE\x10\x01\x12\x17\n" +
	"\x13MERGE_METHOD_SQUASH\x10\x02\x12\x17\n" +
	"\x13MERGE_METHOD_REBASE\x10\x032\xbb\r\n" +
	"\x13MergeRequestService\x12\x8c\x01\n" +
	"\x11ListMergeRequests\x12(.gitprovider.v1.ListMergeRequestsRequest\x1a).gitprovider.v1.ListMergeRequestsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/merge-requests/list\x12\x85\x01\n" +
	"\x0fGetMergeRequest\x12&.gitprovider.v1.GetMergeRequestRequest\x1a'.gitprovider.v1.GetMergeRequestResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/merge-requests/get\x12\x91\x01\n" +
	"\x12CreateMergeRequest\x12).gitprovider.v1.CreateMergeRequestRequest\x1a*.gitprovider.v1.CreateMergeRequestResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/merge-requests/create\x12\x91\x01\n" +
	"\x12UpdateMergeRequest\x12).gitprovider.v1.UpdateMergeRequestRequest\x1a*.gitprovider.v1.UpdateMergeRequestResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/merge-requests/update\x12\x8d\x01\n" +
	"\x11MergeMergeRequest\x12(.gitprovider.v1.MergeMergeRequestRequest\x1a).gitprovider.v1.MergeMergeRequestResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/merge-requests/merge\x12\x92\x01\n" +
	"\x13GetMergeRequestDiff\x12*.gitprovider.v1.GetMergeRequestDiffRequest\x1a+.gitprovider.v1.GetMergeRequestDiffResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/merge-requests/diff\x12\x82\x01\n" +
	"\vListReviews\x12\".gitprovider.v1.ListReviewsRequest\x1a#.gitprovider.v1.ListReviewsResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/merge-requests/reviews/list\x12\x87\x01\n" +
	"\fSubmitReview\x12#.gitprovider.v1.SubmitReviewRequest\x1a$.gitprovider.v1.SubmitReviewResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/merge-requests/reviews/submit\x12\x86\x01\n" +
	"\fListComments\x12#.gitprovider.v1.ListCommentsRequest\x1a$.gitprovider.v1.ListCommentsResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/merge-requests/comments/list\x12\x8b\x01\n" +
	"\rCreateComment\x12$.gitprovider.v1.CreateCommentRequest\x1a%.gitprovider.v1.CreateCommentResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/merge-requests/comments/create\x12\x8b\x01\n" +
	"\rUpdateComment\x12$.gitprovider.v1.UpdateCommentRequest\x1a%.gitprovider.v1.UpdateCommentResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/merge-requests/comments/update\x12\x8b\x01\n" +
	"\rDeleteComment\x12$.gitprovider.v1.DeleteCommentRequest\x1a%.gitprovider.v1.DeleteCommentResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/merge-requests/comments/deleteB5Z3github.com/runners-high/git-provider/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_v1_mergerequest_proto_rawDescOnce sync.Once
	file_v1_mergerequest_proto_rawDescData []byte
)

func file_v1_mergerequest_proto_rawDescGZIP() []byte {
	file_v1_mergerequest_proto_rawDescOnce.Do(func() {
		file_v1_mergerequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_mergerequest_proto_rawDesc), len(file_v1_mergerequest_proto_rawDesc)))
	})
	return file_v1_mergerequest_proto_rawDescData
}

var file_v1_mergerequest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_mergerequest_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_v1_mergerequest_proto_goTypes = []any{
	(MergeRequestState)(0),              // 0: gitprovider.v1.MergeRequestState
	(ReviewState)(0),                    // 1: gitprovider.v1.ReviewState
	(MergeMethod)(0),                    // 2: gitprovider.v1.MergeMethod
	(*MergeRequest)(nil),                // 3: gitprovider.v1.MergeRequest
	(*User)(nil),                        // 4: gitprovider.v1.User
	(*MergeRequestDiff)(nil),            // 5: gitprovider.v1.MergeRequestDiff
	(*FileDiff)(nil),                    // 6: gitprovider.v1.FileDiff
	(*Review)(nil),                      // 7: gitprovider.v1.Review
	(*Comment)(nil),                     // 8: gitprovider.v1.Comment
	(*ListMergeRequestsRequest)(nil),    // 9: gitprovider.v1.ListMergeRequestsRequest
	(*ListMergeRequestsResponse)(nil),   // 10: gitprovider.v1.ListMergeRequestsResponse
	(*GetMergeRequestRequest)(nil),      // 11: gitprovider.v1.GetMergeRequestRequest
	(*GetMergeRequestResponse)(nil),     // 12: gitprovider.v1.GetMergeRequestResponse
	(*CreateMergeRequestRequest)(nil),   // 13: gitprovider.v1.CreateMergeRequestRequest
	(*CreateMergeRequestResponse)(nil),  // 14: gitprovider.v1.CreateMergeRequestResponse
	(*UpdateMergeRequestRequest)(nil),   // 15: gitprovider.v1.UpdateMergeRequestRequest
	(*UpdateMergeRequestResponse)(nil),  // 16: gitprovider.v1.UpdateMergeRequestResponse
	(*MergeMergeRequestRequest)(nil),    // 17: gitprovider.v1.MergeMergeRequestRequest
	(*MergeMergeRequestResponse)(nil),   // 18: gitprovider.v1.MergeMergeRequestResponse
	(*GetMergeRequestDiffRequest)(nil),  // 19: gitprovider.v1.GetMergeRequestDiffRequest
	(*GetMergeRequestDiffResponse)(nil), // 20: gitprovider.v1.GetMergeRequestDiffResponse
	(*ListReviewsRequest)(nil),          // 21: gitprovider.v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),         // 22: gitprovider.v1.ListReviewsResponse
	(*SubmitReviewRequest)(nil),         // 23: gitprovider.v1.SubmitReviewRequest
	(*SubmitReviewResponse)(nil),        // 24: gitprovider.v1.SubmitReviewResponse
	(*ListCommentsRequest)(nil),         // 25: gitprovider.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),        // 26: gitprovider.v1.ListCommentsResponse
	(*CreateCommentRequest)(nil),        // 27: gitprovider.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil),       // 28: gitprovider.v1.CreateCommentResponse
	(*UpdateCommentRequest)(nil),        // 29: gitprovider.v1.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),       // 30: gitprovider.v1.UpdateCommentResponse
	(*DeleteCommentRequest)(nil),        // 31: gitprovider.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),       // 32: gitprovider.v1.DeleteCommentResponse
	(*ProviderConfig)(nil),              // 33: gitprovider.v1.ProviderConfig
}
var file_v1_mergerequest_proto_depIdxs = []int32{
	0,  // 0: gitprovider.v1.MergeRequest.state:type_name -> gitprovider.v1.MergeRequestState
	4,  // 1: gitprovider.v1.MergeRequest.author:type_name -> gitprovider.v1.User
	4,  // 2: gitprovider.v1.MergeRequest.assignees:type_name -> gitprovider.v1.User
	4,  // 3: gitprovider.v1.MergeRequest.reviewers:type_name -> gitprovider.v1.User
	4,  // 4: gitprovider.v1.MergeRequest.merged_by:type_name -> gitprovider.v1.User
	6,  // 5: gitprovider.v1.MergeRequestDiff.files:type_name -> gitprovider.v1.FileDiff
	4,  // 6: gitprovider.v1.Review.user:type_name -> gitprovider.v1.User
	1,  // 7: gitprovider.v1.Review.state:type_name -> gitprovider.v1.ReviewState
	4,  // 8: gitprovider.v1.Comment.user:type_name -> gitprovider.v1.User
	33, // 9: gitprovider.v1.ListMergeRequestsRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	0,  // 10: gitprovider.v1.ListMergeRequestsRequest.state:type_name -> gitprovider.v1.MergeRequestState
	3,  // 11: gitprovider.v1.ListMergeRequestsResponse.merge_requests:type_name -> gitprovider.v1.MergeRequest
	33, // 12: gitprovider.v1.GetMergeRequestRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	3,  // 13: gitprovider.v1.GetMergeRequestResponse.merge_request:type_name -> gitprovider.v1.MergeRequest
	33, // 14: gitprovider.v1.CreateMergeRequestRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	3,  // 15: gitprovider.v1.CreateMergeRequestResponse.merge_request:type_name -> gitprovider.v1.MergeRequest
	33, // 16: gitprovider.v1.UpdateMergeRequestRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	0,  // 17: gitprovider.v1.UpdateMergeRequestRequest.state:type_name -> gitprovider.v1.MergeRequestState
	3,  // 18: gitprovider.v1.UpdateMergeRequestResponse.merge_request:type_name -> gitprovider.v1.MergeRequest
	33, // 19: gitprovider.v1.MergeMergeRequestRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	2,  // 20: gitprovider.v1.MergeMergeRequestRequest.merge_method:type_name -> gitprovider.v1.MergeMethod
	3,  // 21: gitprovider.v1.MergeMergeRequestResponse.merge_request:type_name -> gitprovider.v1.MergeRequest
	33, // 22: gitprovider.v1.GetMergeRequestDiffRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	5,  // 23: gitprovider.v1.GetMergeRequestDiffResponse.diff:type_name -> gitprovider.v1.MergeRequestDiff
	33, // 24: gitprovider.v1.ListReviewsRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	7,  // 25: gitprovider.v1.ListReviewsResponse.reviews:type_name -> gitprovider.v1.Review
	33, // 26: gitprovider.v1.SubmitReviewRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	1,  // 27: gitprovider.v1.SubmitReviewRequest.state:type_name -> gitprovider.v1.ReviewState
	7,  // 28: gitprovider.v1.SubmitReviewResponse.review:type_name -> gitprovider.v1.Review
	33, // 29: gitprovider.v1.ListCommentsRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	8,  // 30: gitprovider.v1.ListCommentsResponse.comments:type_name -> gitprovider.v1.Comment
	33, // 31: gitprovider.v1.CreateCommentRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	8,  // 32: gitprovider.v1.CreateCommentResponse.comment:type_name -> gitprovider.v1.Comment
	33, // 33: gitprovider.v1.UpdateCommentRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	8,  // 34: gitprovider.v1.UpdateCommentResponse.comment:type_name -> gitprovider.v1.Comment
	33, // 35: gitprovider.v1.DeleteCommentRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	9,  // 36: gitprovider.v1.MergeRequestService.ListMergeRequests:input_type -> gitprovider.v1.ListMergeRequestsRequest
	11, // 37: gitprovider.v1.MergeRequestService.GetMergeRequest:input_type -> gitprovider.v1.GetMergeRequestRequest
	13, // 38: gitprovider.v1.MergeRequestService.CreateMergeRequest:input_type -> gitprovider.v1.CreateMergeRequestRequest
	15, // 39: gitprovider.v1.MergeRequestService.UpdateMergeRequest:input_type -> gitprovider.v1.UpdateMergeRequestRequest
	17, // 40: gitprovider.v1.MergeRequestService.MergeMergeRequest:input_type -> gitprovider.v1.MergeMergeRequestRequest
	19, // 41: gitprovider.v1.MergeRequestService.GetMergeRequestDiff:input_type -> gitprovider.v1.GetMergeRequestDiffRequest
	21, // 42: gitprovider.v1.MergeRequestService.ListReviews:input_type -> gitprovider.v1.ListReviewsRequest
	23, // 43: gitprovider.v1.MergeRequestService.SubmitReview:input_type -> gitprovider.v1.SubmitReviewRequest
	25, // 44: gitprovider.v1.MergeRequestService.ListComments:input_type -> gitprovider.v1.ListCommentsRequest
	27, // 45: gitprovider.v1.MergeRequestService.CreateComment:input_type -> gitprovider.v1.CreateCommentRequest
	29, // 46: gitprovider.v1.MergeRequestService.UpdateComment:input_type -> gitprovider.v1.UpdateCommentRequest
	31, // 47: gitprovider.v1.MergeRequestService.DeleteComment:input_type -> gitprovider.v1.DeleteCommentRequest
	10, // 48: gitprovider.v1.MergeRequestService.ListMergeRequests:output_type -> gitprovider.v1.ListMergeRequestsResponse
	12, // 49: gitprovider.v1.MergeRequestService.GetMergeRequest:output_type -> gitprovider.v1.GetMergeRequestResponse
	14, // 50: gitprovider.v1.MergeRequestService.CreateMergeRequest:output_type -> gitprovider.v1.CreateMergeRequestResponse
	16, // 51: gitprovider.v1.MergeRequestService.UpdateMergeRequest:output_type -> gitprovider.v1.UpdateMergeRequestResponse
	18, // 52: gitprovider.v1.MergeRequestService.MergeMergeRequest:output_type -> gitprovider.v1.MergeMergeRequestResponse
	20, // 53: gitprovider.v1.MergeRequestService.GetMergeRequestDiff:output_type -> gitprovider.v1.GetMergeRequestDiffResponse
	22, // 54: gitprovider.v1.MergeRequestService.ListReviews:output_type -> gitprovider.v1.ListReviewsResponse
	24, // 55: gitprovider.v1.MergeRequestService.SubmitReview:output_type -> gitprovider.v1.SubmitReviewResponse
	26, // 56: gitprovider.v1.MergeRequestService.ListComments:output_type -> gitprovider.v1.ListCommentsResponse
	28, // 57: gitprovider.v1.MergeRequestService.CreateComment:output_type -> gitprovider.v1.CreateCommentResponse
	30, // 58: gitprovider.v1.MergeRequestService.UpdateComment:output_type -> gitprovider.v1.UpdateCommentResponse
	32, // 59: gitprovider.v1.MergeRequestService.DeleteComment:output_type -> gitprovider.v1.DeleteCommentResponse
	48, // [48:60] is the sub-list for method output_type
	36, // [36:48] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_v1_mergerequest_proto_init() }
func file_v1_mergerequest_proto_init() {
	if File_v1_mergerequest_proto != nil {
		return
	}
	file_v1_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_mergerequest_proto_rawDesc), len(file_v1_mergerequest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_mergerequest_proto_goTypes,
		DependencyIndexes: file_v1_mergerequest_proto_depIdxs,
		EnumInfos:         file_v1_mergerequest_proto_enumTypes,
		MessageInfos:      file_v1_mergerequest_proto_msgTypes,
	}.Build()
	File_v1_mergerequest_proto = out.File
	file_v1_mergerequest_proto_goTypes = nil
	file_v1_mergerequest_proto_depIdxs = nil
}
