// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: v1/mergerequest.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MergeRequestService_ListMergeRequests_FullMethodName   = "/gitprovider.v1.MergeRequestService/ListMergeRequests"
	MergeRequestService_GetMergeRequest_FullMethodName     = "/gitprovider.v1.MergeRequestService/GetMergeRequest"
	MergeRequestService_CreateMergeRequest_FullMethodName  = "/gitprovider.v1.MergeRequestService/CreateMergeRequest"
	MergeRequestService_UpdateMergeRequest_FullMethodName  = "/gitprovider.v1.MergeRequestService/UpdateMergeRequest"
	MergeRequestService_MergeMergeRequest_FullMethodName   = "/gitprovider.v1.MergeRequestService/MergeMergeRequest"
	MergeRequestService_GetMergeRequestDiff_FullMethodName = "/gitprovider.v1.MergeRequestService/GetMergeRequestDiff"
	MergeRequestService_ListReviews_FullMethodName         = "/gitprovider.v1.MergeRequestService/ListReviews"
	MergeRequestService_SubmitReview_FullMethodName        = "/gitprovider.v1.MergeRequestService/SubmitReview"
	MergeRequestService_ListComments_FullMethodName        = "/gitprovider.v1.MergeRequestService/ListComments"
	MergeRequestService_CreateComment_FullMethodName       = "/gitprovider.v1.MergeRequestService/CreateComment"
	MergeRequestService_UpdateComment_FullMethodName       = "/gitprovider.v1.MergeRequestService/UpdateComment"
	MergeRequestService_DeleteComment_FullMethodName       = "/gitprovider.v1.MergeRequestService/DeleteComment"
)

// MergeRequestServiceClient is the client API for MergeRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MergeRequestServiceClient interface {
	// MR 목록 조회
	ListMergeRequests(ctx context.Context, in *ListMergeRequestsRequest, opts ...grpc.CallOption) (*ListMergeRequestsResponse, error)
	// MR 상세 조회
	GetMergeRequest(ctx context.Context, in *GetMergeRequestRequest, opts ...grpc.CallOption) (*GetMergeRequestResponse, error)
	// MR 생성
	CreateMergeRequest(ctx context.Context, in *CreateMergeRequestRequest, opts ...grpc.CallOption) (*CreateMergeRequestResponse, error)
	// MR 수정
	UpdateMergeRequest(ctx context.Context, in *UpdateMergeRequestRequest, opts ...grpc.CallOption) (*UpdateMergeRequestResponse, error)
	// MR 머지
	MergeMergeRequest(ctx context.Context, in *MergeMergeRequestRequest, opts ...grpc.CallOption) (*MergeMergeRequestResponse, error)
	// MR Diff 조회
	GetMergeRequestDiff(ctx context.Context, in *GetMergeRequestDiffRequest, opts ...grpc.CallOption) (*GetMergeRequestDiffResponse, error)
	// 리뷰 목록 조회
	ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error)
	// 리뷰 제출
	SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*SubmitReviewResponse, error)
	// 댓글 목록 조회
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	// 댓글 생성
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	// 댓글 수정
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	// 댓글 삭제
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type mergeRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMergeRequestServiceClient(cc grpc.ClientConnInterface) MergeRequestServiceClient {
	return &mergeRequestServiceClient{cc}
}

func (c *mergeRequestServiceClient) ListMergeRequests(ctx context.Context, in *ListMergeRequestsRequest, opts ...grpc.CallOption) (*ListMergeRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMergeRequestsResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_ListMergeRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) GetMergeRequest(ctx context.Context, in *GetMergeRequestRequest, opts ...grpc.CallOption) (*GetMergeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMergeRequestResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_GetMergeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) CreateMergeRequest(ctx context.Context, in *CreateMergeRequestRequest, opts ...grpc.CallOption) (*CreateMergeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMergeRequestResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_CreateMergeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) UpdateMergeRequest(ctx context.Context, in *UpdateMergeRequestRequest, opts ...grpc.CallOption) (*UpdateMergeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMergeRequestResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_UpdateMergeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) MergeMergeRequest(ctx context.Context, in *MergeMergeRequestRequest, opts ...grpc.CallOption) (*MergeMergeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeMergeRequestResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_MergeMergeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) GetMergeRequestDiff(ctx context.Context, in *GetMergeRequestDiffRequest, opts ...grpc.CallOption) (*GetMergeRequestDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMergeRequestDiffResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_GetMergeRequestDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewsResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_ListReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*SubmitReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitReviewResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_SubmitReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeRequestServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, MergeRequestService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergeRequestServiceServer is the server API for MergeRequestService service.
// All implementations must embed UnimplementedMergeRequestServiceServer
// for forward compatibility.
type MergeRequestServiceServer interface {
	// MR 목록 조회
	ListMergeRequests(context.Context, *ListMergeRequestsRequest) (*ListMergeRequestsResponse, error)
	// MR 상세 조회
	GetMergeRequest(context.Context, *GetMergeRequestRequest) (*GetMergeRequestResponse, error)
	// MR 생성
	CreateMergeRequest(context.Context, *CreateMergeRequestRequest) (*CreateMergeRequestResponse, error)
	// MR 수정
	UpdateMergeRequest(context.Context, *UpdateMergeRequestRequest) (*UpdateMergeRequestResponse, error)
	// MR 머지
	MergeMergeRequest(context.Context, *MergeMergeRequestRequest) (*MergeMergeRequestResponse, error)
	// MR Diff 조회
	GetMergeRequestDiff(context.Context, *GetMergeRequestDiffRequest) (*GetMergeRequestDiffResponse, error)
	// 리뷰 목록 조회
	ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsResponse, error)
	// 리뷰 제출
	SubmitReview(context.Context, *SubmitReviewRequest) (*SubmitReviewResponse, error)
	// 댓글 목록 조회
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	// 댓글 생성
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	// 댓글 수정
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	// 댓글 삭제
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedMergeRequestServiceServer()
}

// UnimplementedMergeRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMergeRequestServiceServer struct{}

func (UnimplementedMergeRequestServiceServer) ListMergeRequests(context.Context, *ListMergeRequestsRequest) (*ListMergeRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMergeRequests not implemented")
}
func (UnimplementedMergeRequestServiceServer) GetMergeRequest(context.Context, *GetMergeRequestRequest) (*GetMergeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMergeRequest not implemented")
}
func (UnimplementedMergeRequestServiceServer) CreateMergeRequest(context.Context, *CreateMergeRequestRequest) (*CreateMergeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMergeRequest not implemented")
}
func (UnimplementedMergeRequestServiceServer) UpdateMergeRequest(context.Context, *UpdateMergeRequestRequest) (*UpdateMergeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMergeRequest not implemented")
}
func (UnimplementedMergeRequestServiceServer) MergeMergeRequest(context.Context, *MergeMergeRequestRequest) (*MergeMergeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeMergeRequest not implemented")
}
func (UnimplementedMergeRequestServiceServer) GetMergeRequestDiff(context.Context, *GetMergeRequestDiffRequest) (*GetMergeRequestDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMergeRequestDiff not implemented")
}
func (UnimplementedMergeRequestServiceServer) ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReviews not implemented")
}
func (UnimplementedMergeRequestServiceServer) SubmitReview(context.Context, *SubmitReviewRequest) (*SubmitReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitReview not implemented")
}
func (UnimplementedMergeRequestServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedMergeRequestServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedMergeRequestServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedMergeRequestServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedMergeRequestServiceServer) mustEmbedUnimplementedMergeRequestServiceServer() {}
func (UnimplementedMergeRequestServiceServer) testEmbeddedByValue()                             {}

// UnsafeMergeRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergeRequestServiceServer will
// result in compilation errors.
type UnsafeMergeRequestServiceServer interface {
	mustEmbedUnimplementedMergeRequestServiceServer()
}

func RegisterMergeRequestServiceServer(s grpc.ServiceRegistrar, srv MergeRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedMergeRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MergeRequestService_ServiceDesc, srv)
}

func _MergeRequestService_ListMergeRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMergeRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).ListMergeRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_ListMergeRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).ListMergeRequests(ctx, req.(*ListMergeRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_GetMergeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMergeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).GetMergeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_GetMergeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).GetMergeRequest(ctx, req.(*GetMergeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_CreateMergeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMergeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).CreateMergeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_CreateMergeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).CreateMergeRequest(ctx, req.(*CreateMergeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_UpdateMergeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMergeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).UpdateMergeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_UpdateMergeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).UpdateMergeRequest(ctx, req.(*UpdateMergeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_MergeMergeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeMergeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).MergeMergeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_MergeMergeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).MergeMergeRequest(ctx, req.(*MergeMergeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_GetMergeRequestDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMergeRequestDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).GetMergeRequestDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_GetMergeRequestDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).GetMergeRequestDiff(ctx, req.(*GetMergeRequestDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_ListReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).ListReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_ListReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).ListReviews(ctx, req.(*ListReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_SubmitReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).SubmitReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_SubmitReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).SubmitReview(ctx, req.(*SubmitReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergeRequestService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeRequestServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeRequestService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeRequestServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MergeRequestService_ServiceDesc is the grpc.ServiceDesc for MergeRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MergeRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitprovider.v1.MergeRequestService",
	HandlerType: (*MergeRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMergeRequests",
			Handler:    _MergeRequestService_ListMergeRequests_Handler,
		},
		{
			MethodName: "GetMergeRequest",
			Handler:    _MergeRequestService_GetMergeRequest_Handler,
		},
		{
			MethodName: "CreateMergeRequest",
			Handler:    _MergeRequestService_CreateMergeRequest_Handler,
		},
		{
			MethodName: "UpdateMergeRequest",
			Handler:    _MergeRequestService_UpdateMergeRequest_Handler,
		},
		{
			MethodName: "MergeMergeRequest",
			Handler:    _MergeRequestService_MergeMergeRequest_Handler,
		},
		{
			MethodName: "GetMergeRequestDiff",
			Handler:    _MergeRequestService_GetMergeRequestDiff_Handler,
		},
		{
			MethodName: "ListReviews",
			Handler:    _MergeRequestService_ListReviews_Handler,
		},
		{
			MethodName: "SubmitReview",
			Handler:    _MergeRequestService_SubmitReview_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _MergeRequestService_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _MergeRequestService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _MergeRequestService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _MergeRequestService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/mergerequest.proto",
}
