// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: v1/provider.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_GITHUB      ProviderType = 1
	ProviderType_PROVIDER_TYPE_GITLAB      ProviderType = 2
	ProviderType_PROVIDER_TYPE_BITBUCKET   ProviderType = 3
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_GITHUB",
		2: "PROVIDER_TYPE_GITLAB",
		3: "PROVIDER_TYPE_BITBUCKET",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_GITHUB":      1,
		"PROVIDER_TYPE_GITLAB":      2,
		"PROVIDER_TYPE_BITBUCKET":   3,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_v1_provider_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{0}
}

type NamespaceType int32

const (
	NamespaceType_NAMESPACE_TYPE_UNSPECIFIED  NamespaceType = 0
	NamespaceType_NAMESPACE_TYPE_USER         NamespaceType = 1 // GitHub User, GitLab User
	NamespaceType_NAMESPACE_TYPE_ORGANIZATION NamespaceType = 2 // GitHub Organization
	NamespaceType_NAMESPACE_TYPE_GROUP        NamespaceType = 3 // GitLab Group
	NamespaceType_NAMESPACE_TYPE_WORKSPACE    NamespaceType = 4 // Bitbucket Workspace
)

// Enum value maps for NamespaceType.
var (
	NamespaceType_name = map[int32]string{
		0: "NAMESPACE_TYPE_UNSPECIFIED",
		1: "NAMESPACE_TYPE_USER",
		2: "NAMESPACE_TYPE_ORGANIZATION",
		3: "NAMESPACE_TYPE_GROUP",
		4: "NAMESPACE_TYPE_WORKSPACE",
	}
	NamespaceType_value = map[string]int32{
		"NAMESPACE_TYPE_UNSPECIFIED":  0,
		"NAMESPACE_TYPE_USER":         1,
		"NAMESPACE_TYPE_ORGANIZATION": 2,
		"NAMESPACE_TYPE_GROUP":        3,
		"NAMESPACE_TYPE_WORKSPACE":    4,
	}
)

func (x NamespaceType) Enum() *NamespaceType {
	p := new(NamespaceType)
	*p = x
	return p
}

func (x NamespaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamespaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_provider_proto_enumTypes[1].Descriptor()
}

func (NamespaceType) Type() protoreflect.EnumType {
	return &file_v1_provider_proto_enumTypes[1]
}

func (x NamespaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NamespaceType.Descriptor instead.
func (NamespaceType) EnumDescriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{1}
}

type GitHubConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // 선택: Enterprise URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubConfig) Reset() {
	*x = GitHubConfig{}
	mi := &file_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubConfig) ProtoMessage() {}

func (x *GitHubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubConfig.ProtoReflect.Descriptor instead.
func (*GitHubConfig) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GitHubConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitHubConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type GitLabConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // 선택: Self-hosted URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLabConfig) Reset() {
	*x = GitLabConfig{}
	mi := &file_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLabConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLabConfig) ProtoMessage() {}

func (x *GitLabConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLabConfig.ProtoReflect.Descriptor instead.
func (*GitLabConfig) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GitLabConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitLabConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type BitbucketConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API Token 인증 (2025년 9월 9일부터 권장)
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                       // Atlassian 계정 이메일
	ApiToken      string `protobuf:"bytes,2,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"` // API Token (ATAT... 형식)
	Workspace     string `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`               // Workspace 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitbucketConfig) Reset() {
	*x = BitbucketConfig{}
	mi := &file_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitbucketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitbucketConfig) ProtoMessage() {}

func (x *BitbucketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitbucketConfig.ProtoReflect.Descriptor instead.
func (*BitbucketConfig) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *BitbucketConfig) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BitbucketConfig) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *BitbucketConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

// 프로바이더 설정 (하나만 선택)
type ProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*ProviderConfig_Github
	//	*ProviderConfig_Gitlab
	//	*ProviderConfig_Bitbucket
	Config        isProviderConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderConfig) GetConfig() isProviderConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProviderConfig) GetGithub() *GitHubConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Github); ok {
			return x.Github
		}
	}
	return nil
}

func (x *ProviderConfig) GetGitlab() *GitLabConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Gitlab); ok {
			return x.Gitlab
		}
	}
	return nil
}

func (x *ProviderConfig) GetBitbucket() *BitbucketConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Bitbucket); ok {
			return x.Bitbucket
		}
	}
	return nil
}

type isProviderConfig_Config interface {
	isProviderConfig_Config()
}

type ProviderConfig_Github struct {
	Github *GitHubConfig `protobuf:"bytes,1,opt,name=github,proto3,oneof"`
}

type ProviderConfig_Gitlab struct {
	Gitlab *GitLabConfig `protobuf:"bytes,2,opt,name=gitlab,proto3,oneof"`
}

type ProviderConfig_Bitbucket struct {
	Bitbucket *BitbucketConfig `protobuf:"bytes,3,opt,name=bitbucket,proto3,oneof"`
}

func (*ProviderConfig_Github) isProviderConfig_Config() {}

func (*ProviderConfig_Gitlab) isProviderConfig_Config() {}

func (*ProviderConfig_Bitbucket) isProviderConfig_Config() {}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,3,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	Config        *ProviderConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *Provider) GetConfig() *ProviderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Provider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Provider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RegisterProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,2,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	Config        *ProviderConfig        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderRequest) Reset() {
	*x = RegisterProviderRequest{}
	mi := &file_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderRequest) ProtoMessage() {}

func (x *RegisterProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterProviderRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *RegisterProviderRequest) GetConfig() *ProviderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegisterProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderResponse) Reset() {
	*x = RegisterProviderResponse{}
	mi := &file_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderResponse) ProtoMessage() {}

func (x *RegisterProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *GetProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProviderType           `protobuf:"varint,1,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ListProvidersRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderResponse) Reset() {
	*x = DeleteProviderResponse{}
	mi := &file_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderResponse) ProtoMessage() {}

func (x *DeleteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Namespace는 저장소의 소유자 정보를 통합합니다.
// - GitHub: User 또는 Organization
// - GitLab: User 또는 Group (중첩 가능)
// - Bitbucket: Workspace
type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 고유 식별자
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                    // 표시 이름 (login, slug)
	FullPath      string                 `protobuf:"bytes,3,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`            // 전체 경로 (GitLab 중첩 그룹 지원: "group/subgroup")
	Type          NamespaceType          `protobuf:"varint,4,opt,name=type,proto3,enum=gitprovider.v1.NamespaceType" json:"type,omitempty"` // 소유자 유형
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`         // 아바타 이미지 URL
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`                                      // 프로필 페이지 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *Namespace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *Namespace) GetType() NamespaceType {
	if x != nil {
		return x.Type
	}
	return NamespaceType_NAMESPACE_TYPE_UNSPECIFIED
}

func (x *Namespace) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Namespace) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Repository는 모든 프로바이더의 저장소를 통합합니다.
// - GitHub: Repository
// - GitLab: Project
// - Bitbucket: Repository
type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 고유 식별자
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 저장소 이름
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`                // 전체 이름 (owner/repo)
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                          // 설명
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                          // 웹 URL (html_url)
	CloneUrl      string                 `protobuf:"bytes,6,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`                // HTTPS clone URL
	DefaultBranch string                 `protobuf:"bytes,7,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"` // 기본 브랜치명
	Private       bool                   `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`                                 // 비공개 여부
	// === 새로 추가된 필드 ===
	SshUrl        string       `protobuf:"bytes,9,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`                          // SSH clone URL
	Namespace     *Namespace   `protobuf:"bytes,10,opt,name=namespace,proto3" json:"namespace,omitempty"`                                 // 소유자 정보
	CreatedAt     string       `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 생성 시간 (ISO 8601)
	UpdatedAt     string       `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 수정 시간 (ISO 8601)
	Provider      ProviderType `protobuf:"varint,13,opt,name=provider,proto3,enum=gitprovider.v1.ProviderType" json:"provider,omitempty"` // 원본 프로바이더
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *Repository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Repository) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *Repository) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Repository) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Repository) GetProvider() ProviderType {
	if x != nil {
		return x.Provider
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

// Commit은 브랜치의 마지막 커밋 정보를 담습니다.
type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`                                    // 커밋 SHA (전체 40자)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                            // 커밋 메시지
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`    // 작성자 이름
	AuthorEmail   string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"` // 작성자 이메일
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`                                  // 작성 시간 (ISO 8601)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *Commit) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Commit) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Commit) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Branch는 모든 프로바이더의 브랜치를 통합합니다.
type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 브랜치 이름
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`                                 // 마지막 커밋 SHA
	Protected     bool                   `protobuf:"varint,3,opt,name=protected,proto3" json:"protected,omitempty"`                    // 보호 브랜치 여부
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`   // 기본 브랜치 여부
	LastCommit    *Commit                `protobuf:"bytes,5,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"` // 마지막 커밋 정보 (선택)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *Branch) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Branch) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Branch) GetLastCommit() *Commit {
	if x != nil {
		return x.LastCommit
	}
	return nil
}

// 저장소 목록 조회
type ListRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // 프로바이더 설정
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ListRepositoriesRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// 저장소 상세 조회
type GetRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자 (owner/workspace)
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *GetRepositoryRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetRepositoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type GetRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

// 저장소 생성
type CreateRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                  // 프로바이더 설정
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                          // 저장소 이름
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`            // 설명 (선택)
	Private       bool                   `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`                   // 비공개 여부
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`                // 소유자 (선택, 조직/그룹에 생성 시)
	AutoInit      bool                   `protobuf:"varint,6,opt,name=auto_init,json=autoInit,proto3" json:"auto_init,omitempty"` // README 자동 생성
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryRequest) Reset() {
	*x = CreateRepositoryRequest{}
	mi := &file_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryRequest) ProtoMessage() {}

func (x *CreateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*CreateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRepositoryRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *CreateRepositoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepositoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRepositoryRequest) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *CreateRepositoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateRepositoryRequest) GetAutoInit() bool {
	if x != nil {
		return x.AutoInit
	}
	return false
}

type CreateRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryResponse) Reset() {
	*x = CreateRepositoryResponse{}
	mi := &file_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryResponse) ProtoMessage() {}

func (x *CreateRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryResponse.ProtoReflect.Descriptor instead.
func (*CreateRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

// 저장소 삭제
type DeleteRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryRequest) Reset() {
	*x = DeleteRepositoryRequest{}
	mi := &file_v1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryRequest) ProtoMessage() {}

func (x *DeleteRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteRepositoryRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *DeleteRepositoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRepositoryRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type DeleteRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryResponse) Reset() {
	*x = DeleteRepositoryResponse{}
	mi := &file_v1_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryResponse) ProtoMessage() {}

func (x *DeleteRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRepositoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 브랜치 목록 조회
type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_v1_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{25}
}

func (x *ListBranchesRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ListBranchesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListBranchesRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_v1_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{26}
}

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

// 브랜치 상세 조회
type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`         // 브랜치 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_v1_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{27}
}

func (x *GetBranchRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetBranchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetBranchRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type GetBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchResponse) Reset() {
	*x = GetBranchResponse{}
	mi := &file_v1_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchResponse) ProtoMessage() {}

func (x *GetBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchResponse.ProtoReflect.Descriptor instead.
func (*GetBranchResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{28}
}

func (x *GetBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

// 브랜치 생성
type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`         // 새 브랜치 이름
	Ref           string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`               // 시작점 (브랜치명 또는 커밋 SHA)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_v1_provider_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{29}
}

func (x *CreateBranchRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *CreateBranchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateBranchRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CreateBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateBranchRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_v1_provider_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{30}
}

func (x *CreateBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

// 브랜치 삭제
type DeleteBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // 프로바이더 설정
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 소유자
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // 저장소 이름
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`         // 브랜치 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchRequest) Reset() {
	*x = DeleteBranchRequest{}
	mi := &file_v1_provider_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchRequest) ProtoMessage() {}

func (x *DeleteBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBranchRequest) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteBranchRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *DeleteBranchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteBranchRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DeleteBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type DeleteBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchResponse) Reset() {
	*x = DeleteBranchResponse{}
	mi := &file_v1_provider_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchResponse) ProtoMessage() {}

func (x *DeleteBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provider_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchResponse.ProtoReflect.Descriptor instead.
func (*DeleteBranchResponse) Descriptor() ([]byte, []int) {
	return file_v1_provider_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_provider_proto protoreflect.FileDescriptor

const file_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x11v1/provider.proto\x12\x0egitprovider.v1\x1a\x1cgoogle/api/annotations.proto\"?\n" +
	"\fGitHubConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"?\n" +
	"\fGitLabConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"b\n" +
	"\x0fBitbucketConfig\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tapi_token\x18\x02 \x01(\tR\bapiToken\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\"\xcb\x01\n" +
	"\x0eProviderConfig\x126\n" +
	"\x06github\x18\x01 \x01(\v2\x1c.gitprovider.v1.GitHubConfigH\x00R\x06github\x126\n" +
	"\x06gitlab\x18\x02 \x01(\v2\x1c.gitprovider.v1.GitLabConfigH\x00R\x06gitlab\x12?\n" +
	"\tbitbucket\x18\x03 \x01(\v2\x1f.gitprovider.v1.BitbucketConfigH\x00R\tbitbucketB\b\n" +
	"\x06config\"\xd6\x01\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x97\x01\n" +
	"\x17RegisterProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\x06config\"P\n" +
	"\x18RegisterProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.gitprovider.v1.ProviderR\bprovider\"$\n" +
	"\x12GetProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.gitprovider.v1.ProviderR\bprovider\"H\n" +
	"\x14ListProvidersRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\"O\n" +
	"\x15ListProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.gitprovider.v1.ProviderR\tproviders\"'\n" +
	"\x15DeleteProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb0\x01\n" +
	"\tNamespace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_path\x18\x03 \x01(\tR\bfullPath\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.gitprovider.v1.NamespaceTypeR\x04type\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"\xa9\x03\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tclone_url\x18\x06 \x01(\tR\bcloneUrl\x12%\n" +
	"\x0edefault_branch\x18\a \x01(\tR\rdefaultBranch\x12\x18\n" +
	"\aprivate\x18\b \x01(\bR\aprivate\x12\x17\n" +
	"\assh_url\x18\t \x01(\tR\x06sshUrl\x127\n" +
	"\tnamespace\x18\n" +
	" \x01(\v2\x19.gitprovider.v1.NamespaceR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x128\n" +
	"\bprovider\x18\r \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\bprovider\"\x8c\x01\n" +
	"\x06Commit\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"\xa4\x01\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\x12\x1c\n" +
	"\tprotected\x18\x03 \x01(\bR\tprotected\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x127\n" +
	"\vlast_commit\x18\x05 \x01(\v2\x16.gitprovider.v1.CommitR\n" +
	"lastCommit\"U\n" +
	"\x17ListRepositoriesRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\"Z\n" +
	"\x18ListRepositoriesResponse\x12>\n" +
	"\frepositories\x18\x01 \x03(\v2\x1a.gitprovider.v1.RepositoryR\frepositories\"\x90\x01\n" +
	"\x14GetRepositoryRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\"S\n" +
	"\x15GetRepositoryResponse\x12:\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x1a.gitprovider.v1.RepositoryR\n" +
	"repository\"\xe0\x01\n" +
	"\x17CreateRepositoryRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aprivate\x18\x04 \x01(\bR\aprivate\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tauto_init\x18\x06 \x01(\bR\bautoInit\"V\n" +
	"\x18CreateRepositoryResponse\x12:\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x1a.gitprovider.v1.RepositoryR\n" +
	"repository\"\x93\x01\n" +
	"\x17DeleteRepositoryRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\"4\n" +
	"\x18DeleteRepositoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\x13ListBranchesRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\"J\n" +
	"\x14ListBranchesResponse\x122\n" +
	"\bbranches\x18\x01 \x03(\v2\x16.gitprovider.v1.BranchR\bbranches\"\xa4\x01\n" +
	"\x10GetBranchRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\"C\n" +
	"\x11GetBranchResponse\x12.\n" +
	"\x06branch\x18\x01 \x01(\v2\x16.gitprovider.v1.BranchR\x06branch\"\xb9\x01\n" +
	"\x13CreateBranchRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\"F\n" +
	"\x14CreateBranchResponse\x12.\n" +
	"\x06branch\x18\x01 \x01(\v2\x16.gitprovider.v1.BranchR\x06branch\"\xa7\x01\n" +
	"\x13DeleteBranchRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\"0\n" +
	"\x14DeleteBranchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*~\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITHUB\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITLAB\x10\x02\x12\x1b\n" +
	"\x17PROVIDER_TYPE_BITBUCKET\x10\x03*\xa1\x01\n" +
	"\rNamespaceType\x12\x1e\n" +
	"\x1aNAMESPACE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NAMESPACE_TYPE_USER\x10\x01\x12\x1f\n" +
	"\x1bNAMESPACE_TYPE_ORGANIZATION\x10\x02\x12\x18\n" +
	"\x14NAMESPACE_TYPE_GROUP\x10\x03\x12\x1c\n" +
	"\x18NAMESPACE_TYPE_WORKSPACE\x10\x042\xf8\x03\n" +
	"\x0fProviderService\x12\x7f\n" +
	"\x10RegisterProvider\x12'.gitprovider.v1.RegisterProviderRequest\x1a(.gitprovider.v1.RegisterProviderResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/providers\x12r\n" +
	"\vGetProvider\x12\".gitprovider.v1.GetProviderRequest\x1a#.gitprovider.v1.GetProviderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/providers/{id}\x12s\n" +
	"\rListProviders\x12$.gitprovider.v1.ListProvidersRequest\x1a%.gitprovider.v1.ListProvidersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/providers\x12{\n" +
	"\x0eDeleteProvider\x12%.gitprovider.v1.DeleteProviderRequest\x1a&.gitprovider.v1.DeleteProviderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/providers/{id}2\xfd\a\n" +
	"\n" +
	"GitService\x12\x87\x01\n" +
	"\x10ListRepositories\x12'.gitprovider.v1.ListRepositoriesRequest\x1a(.gitprovider.v1.ListRepositoriesResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/repositories/list\x12}\n" +
	"\rGetRepository\x12$.gitprovider.v1.GetRepositoryRequest\x1a%.gitprovider.v1.GetRepositoryResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/repositories/get\x12\x82\x01\n" +
	"\x10CreateRepository\x12'.gitprovider.v1.CreateRepositoryRequest\x1a(.gitprovider.v1.CreateRepositoryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/repositories\x12\x89\x01\n" +
	"\x10DeleteRepository\x12'.gitprovider.v1.DeleteRepositoryRequest\x1a(.gitprovider.v1.DeleteRepositoryResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/repositories/delete\x12w\n" +
	"\fListBranches\x12#.gitprovider.v1.ListBranchesRequest\x1a$.gitprovider.v1.ListBranchesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/branches/list\x12m\n" +
	"\tGetBranch\x12 .gitprovider.v1.GetBranchRequest\x1a!.gitprovider.v1.GetBranchResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/branches/get\x12r\n" +
	"\fCreateBranch\x12#.gitprovider.v1.CreateBranchRequest\x1a$.gitprovider.v1.CreateBranchResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/branches\x12y\n" +
	"\fDeleteBranch\x12#.gitprovider.v1.DeleteBranchRequest\x1a$.gitprovider.v1.DeleteBranchResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/branches/deleteB5Z3github.com/runners-high/git-provider/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_v1_provider_proto_rawDescOnce sync.Once
	file_v1_provider_proto_rawDescData []byte
)

func file_v1_provider_proto_rawDescGZIP() []byte {
	file_v1_provider_proto_rawDescOnce.Do(func() {
		file_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_provider_proto_rawDesc), len(file_v1_provider_proto_rawDesc)))
	})
	return file_v1_provider_proto_rawDescData
}

var file_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_v1_provider_proto_goTypes = []any{
	(ProviderType)(0),                // 0: gitprovider.v1.ProviderType
	(NamespaceType)(0),               // 1: gitprovider.v1.NamespaceType
	(*GitHubConfig)(nil),             // 2: gitprovider.v1.GitHubConfig
	(*GitLabConfig)(nil),             // 3: gitprovider.v1.GitLabConfig
	(*BitbucketConfig)(nil),          // 4: gitprovider.v1.BitbucketConfig
	(*ProviderConfig)(nil),           // 5: gitprovider.v1.ProviderConfig
	(*Provider)(nil),                 // 6: gitprovider.v1.Provider
	(*RegisterProviderRequest)(nil),  // 7: gitprovider.v1.RegisterProviderRequest
	(*RegisterProviderResponse)(nil), // 8: gitprovider.v1.RegisterProviderResponse
	(*GetProviderRequest)(nil),       // 9: gitprovider.v1.GetProviderRequest
	(*GetProviderResponse)(nil),      // 10: gitprovider.v1.GetProviderResponse
	(*ListProvidersRequest)(nil),     // 11: gitprovider.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),    // 12: gitprovider.v1.ListProvidersResponse
	(*DeleteProviderRequest)(nil),    // 13: gitprovider.v1.DeleteProviderRequest
	(*DeleteProviderResponse)(nil),   // 14: gitprovider.v1.DeleteProviderResponse
	(*Namespace)(nil),                // 15: gitprovider.v1.Namespace
	(*Repository)(nil),               // 16: gitprovider.v1.Repository
	(*Commit)(nil),                   // 17: gitprovider.v1.Commit
	(*Branch)(nil),                   // 18: gitprovider.v1.Branch
	(*ListRepositoriesRequest)(nil),  // 19: gitprovider.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 20: gitprovider.v1.ListRepositoriesResponse
	(*GetRepositoryRequest)(nil),     // 21: gitprovider.v1.GetRepositoryRequest
	(*GetRepositoryResponse)(nil),    // 22: gitprovider.v1.GetRepositoryResponse
	(*CreateRepositoryRequest)(nil),  // 23: gitprovider.v1.CreateRepositoryRequest
	(*CreateRepositoryResponse)(nil), // 24: gitprovider.v1.CreateRepositoryResponse
	(*DeleteRepositoryRequest)(nil),  // 25: gitprovider.v1.DeleteRepositoryRequest
	(*DeleteRepositoryResponse)(nil), // 26: gitprovider.v1.DeleteRepositoryResponse
	(*ListBranchesRequest)(nil),      // 27: gitprovider.v1.ListBranchesRequest
	(*ListBranchesResponse)(nil),     // 28: gitprovider.v1.ListBranchesResponse
	(*GetBranchRequest)(nil),         // 29: gitprovider.v1.GetBranchRequest
	(*GetBranchResponse)(nil),        // 30: gitprovider.v1.GetBranchResponse
	(*CreateBranchRequest)(nil),      // 31: gitprovider.v1.CreateBranchRequest
	(*CreateBranchResponse)(nil),     // 32: gitprovider.v1.CreateBranchResponse
	(*DeleteBranchRequest)(nil),      // 33: gitprovider.v1.DeleteBranchRequest
	(*DeleteBranchResponse)(nil),     // 34: gitprovider.v1.DeleteBranchResponse
}
var file_v1_provider_proto_depIdxs = []int32{
	2,  // 0: gitprovider.v1.ProviderConfig.github:type_name -> gitprovider.v1.GitHubConfig
	3,  // 1: gitprovider.v1.ProviderConfig.gitlab:type_name -> gitprovider.v1.GitLabConfig
	4,  // 2: gitprovider.v1.ProviderConfig.bitbucket:type_name -> gitprovider.v1.BitbucketConfig
	0,  // 3: gitprovider.v1.Provider.type:type_name -> gitprovider.v1.ProviderType
	5,  // 4: gitprovider.v1.Provider.config:type_name -> gitprovider.v1.ProviderConfig
	0,  // 5: gitprovider.v1.RegisterProviderRequest.type:type_name -> gitprovider.v1.ProviderType
	5,  // 6: gitprovider.v1.RegisterProviderRequest.config:type_name -> gitprovider.v1.ProviderConfig
	6,  // 7: gitprovider.v1.RegisterProviderResponse.provider:type_name -> gitprovider.v1.Provider
	6,  // 8: gitprovider.v1.GetProviderResponse.provider:type_name -> gitprovider.v1.Provider
	0,  // 9: gitprovider.v1.ListProvidersRequest.type:type_name -> gitprovider.v1.ProviderType
	6,  // 10: gitprovider.v1.ListProvidersResponse.providers:type_name -> gitprovider.v1.Provider
	1,  // 11: gitprovider.v1.Namespace.type:type_name -> gitprovider.v1.NamespaceType
	15, // 12: gitprovider.v1.Repository.namespace:type_name -> gitprovider.v1.Namespace
	0,  // 13: gitprovider.v1.Repository.provider:type_name -> gitprovider.v1.ProviderType
	17, // 14: gitprovider.v1.Branch.last_commit:type_name -> gitprovider.v1.Commit
	5,  // 15: gitprovider.v1.ListRepositoriesRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	16, // 16: gitprovider.v1.ListRepositoriesResponse.repositories:type_name -> gitprovider.v1.Repository
	5,  // 17: gitprovider.v1.GetRepositoryRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	16, // 18: gitprovider.v1.GetRepositoryResponse.repository:type_name -> gitprovider.v1.Repository
	5,  // 19: gitprovider.v1.CreateRepositoryRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	16, // 20: gitprovider.v1.CreateRepositoryResponse.repository:type_name -> gitprovider.v1.Repository
	5,  // 21: gitprovider.v1.DeleteRepositoryRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	5,  // 22: gitprovider.v1.ListBranchesRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	18, // 23: gitprovider.v1.ListBranchesResponse.branches:type_name -> gitprovider.v1.Branch
	5,  // 24: gitprovider.v1.GetBranchRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	18, // 25: gitprovider.v1.GetBranchResponse.branch:type_name -> gitprovider.v1.Branch
	5,  // 26: gitprovider.v1.CreateBranchRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	18, // 27: gitprovider.v1.CreateBranchResponse.branch:type_name -> gitprovider.v1.Branch
	5,  // 28: gitprovider.v1.DeleteBranchRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	7,  // 29: gitprovider.v1.ProviderService.RegisterProvider:input_type -> gitprovider.v1.RegisterProviderRequest
	9,  // 30: gitprovider.v1.ProviderService.GetProvider:input_type -> gitprovider.v1.GetProviderRequest
	11, // 31: gitprovider.v1.ProviderService.ListProviders:input_type -> gitprovider.v1.ListProvidersRequest
	13, // 32: gitprovider.v1.ProviderService.DeleteProvider:input_type -> gitprovider.v1.DeleteProviderRequest
	19, // 33: gitprovider.v1.GitService.ListRepositories:input_type -> gitprovider.v1.ListRepositoriesRequest
	21, // 34: gitprovider.v1.GitService.GetRepository:input_type -> gitprovider.v1.GetRepositoryRequest
	23, // 35: gitprovider.v1.GitService.CreateRepository:input_type -> gitprovider.v1.CreateRepositoryRequest
	25, // 36: gitprovider.v1.GitService.DeleteRepository:input_type -> gitprovider.v1.DeleteRepositoryRequest
	27, // 37: gitprovider.v1.GitService.ListBranches:input_type -> gitprovider.v1.ListBranchesRequest
	29, // 38: gitprovider.v1.GitService.GetBranch:input_type -> gitprovider.v1.GetBranchRequest
	31, // 39: gitprovider.v1.GitService.CreateBranch:input_type -> gitprovider.v1.CreateBranchRequest
	33, // 40: gitprovider.v1.GitService.DeleteBranch:input_type -> gitprovider.v1.DeleteBranchRequest
	8,  // 41: gitprovider.v1.ProviderService.RegisterProvider:output_type -> gitprovider.v1.RegisterProviderResponse
	10, // 42: gitprovider.v1.ProviderService.GetProvider:output_type -> gitprovider.v1.GetProviderResponse
	12, // 43: gitprovider.v1.ProviderService.ListProviders:output_type -> gitprovider.v1.ListProvidersResponse
	14, // 44: gitprovider.v1.ProviderService.DeleteProvider:output_type -> gitprovider.v1.DeleteProviderResponse
	20, // 45: gitprovider.v1.GitService.ListRepositories:output_type -> gitprovider.v1.ListRepositoriesResponse
	22, // 46: gitprovider.v1.GitService.GetRepository:output_type -> gitprovider.v1.GetRepositoryResponse
	24, // 47: gitprovider.v1.GitService.CreateRepository:output_type -> gitprovider.v1.CreateRepositoryResponse
	26, // 48: gitprovider.v1.GitService.DeleteRepository:output_type -> gitprovider.v1.DeleteRepositoryResponse
	28, // 49: gitprovider.v1.GitService.ListBranches:output_type -> gitprovider.v1.ListBranchesResponse
	30, // 50: gitprovider.v1.GitService.GetBranch:output_type -> gitprovider.v1.GetBranchResponse
	32, // 51: gitprovider.v1.GitService.CreateBranch:output_type -> gitprovider.v1.CreateBranchResponse
	34, // 52: gitprovider.v1.GitService.DeleteBranch:output_type -> gitprovider.v1.DeleteBranchResponse
	41, // [41:53] is the sub-list for method output_type
	29, // [29:41] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_v1_provider_proto_init() }
func file_v1_provider_proto_init() {
	if File_v1_provider_proto != nil {
		return
	}
	file_v1_provider_proto_msgTypes[3].OneofWrappers = []any{
		(*ProviderConfig_Github)(nil),
		(*ProviderConfig_Gitlab)(nil),
		(*ProviderConfig_Bitbucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_provider_proto_rawDesc), len(file_v1_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_provider_proto_goTypes,
		DependencyIndexes: file_v1_provider_proto_depIdxs,
		EnumInfos:         file_v1_provider_proto_enumTypes,
		MessageInfos:      file_v1_provider_proto_msgTypes,
	}.Build()
	File_v1_provider_proto = out.File
	file_v1_provider_proto_goTypes = nil
	file_v1_provider_proto_depIdxs = nil
}
