// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: v1/workflow.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED      ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_RUNNING          ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_WAITING_FOR_STEP ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_COMPLETED        ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED           ExecutionStatus = 4
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_RUNNING",
		2: "EXECUTION_STATUS_WAITING_FOR_STEP",
		3: "EXECUTION_STATUS_COMPLETED",
		4: "EXECUTION_STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED":      0,
		"EXECUTION_STATUS_RUNNING":          1,
		"EXECUTION_STATUS_WAITING_FOR_STEP": 2,
		"EXECUTION_STATUS_COMPLETED":        3,
		"EXECUTION_STATUS_FAILED":           4,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_v1_workflow_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type WorkflowFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"` // namespace/repo
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`         // "main", "develop"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowFilter) Reset() {
	*x = WorkflowFilter{}
	mi := &file_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowFilter) ProtoMessage() {}

func (x *WorkflowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowFilter.ProtoReflect.Descriptor instead.
func (*WorkflowFilter) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowFilter) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *WorkflowFilter) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type WorkflowStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 스텝 이름 ("deploy")
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                               // "cicd_build"
	PipelineId    string                 `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"` // 연결된 파이프라인 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkflowStep) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TriggerEvent  string                 `protobuf:"bytes,3,opt,name=trigger_event,json=triggerEvent,proto3" json:"trigger_event,omitempty"` // "mr_merged", "push"
	Filter        *WorkflowFilter        `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetTriggerEvent() string {
	if x != nil {
		return x.TriggerEvent
	}
	return ""
}

func (x *Workflow) GetFilter() *WorkflowFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Workflow) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Workflow) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type StepExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PipelineId    string                 `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "success", "failure"
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecution) Reset() {
	*x = StepExecution{}
	mi := &file_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecution) ProtoMessage() {}

func (x *StepExecution) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecution.ProtoReflect.Descriptor instead.
func (*StepExecution) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *StepExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepExecution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StepExecution) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *StepExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepExecution) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *StepExecution) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=gitprovider.v1.ExecutionStatus" json:"status,omitempty"`
	CurrentStep   int32                  `protobuf:"varint,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Steps         []*StepExecution       `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	TriggerEvent  string                 `protobuf:"bytes,6,opt,name=trigger_event,json=triggerEvent,proto3" json:"trigger_event,omitempty"` // 트리거한 이벤트 타입
	Repository    string                 `protobuf:"bytes,7,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch        string                 `protobuf:"bytes,8,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitSha     string                 `protobuf:"bytes,9,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	StartedAt     string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *Execution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Execution) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *Execution) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *Execution) GetSteps() []*StepExecution {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Execution) GetTriggerEvent() string {
	if x != nil {
		return x.TriggerEvent
	}
	return ""
}

func (x *Execution) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Execution) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Execution) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Execution) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Execution) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TriggerEvent  string                 `protobuf:"bytes,2,opt,name=trigger_event,json=triggerEvent,proto3" json:"trigger_event,omitempty"`
	Filter        *WorkflowFilter        `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTriggerEvent() string {
	if x != nil {
		return x.TriggerEvent
	}
	return ""
}

func (x *CreateWorkflowRequest) GetFilter() *WorkflowFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *CreateWorkflowRequest) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkflowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"` // 선택: 특정 저장소 필터
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorkflowsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type DeleteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowRequest) Reset() {
	*x = DeleteWorkflowRequest{}
	mi := &file_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowRequest) ProtoMessage() {}

func (x *DeleteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkflowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowResponse) Reset() {
	*x = DeleteWorkflowResponse{}
	mi := &file_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowResponse) ProtoMessage() {}

func (x *DeleteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_v1_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionResponse) Reset() {
	*x = GetExecutionResponse{}
	mi := &file_v1_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionResponse) ProtoMessage() {}

func (x *GetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *GetExecutionResponse) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 최대 개수 (기본 20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_v1_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *ListExecutionsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ListExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_v1_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *ListExecutionsResponse) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

var File_v1_workflow_proto protoreflect.FileDescriptor

const file_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x11v1/workflow.proto\x12\x0egitprovider.v1\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\x0eWorkflowFilter\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"W\n" +
	"\fWorkflowStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vpipeline_id\x18\x03 \x01(\tR\n" +
	"pipelineId\"\xfd\x01\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtrigger_event\x18\x03 \x01(\tR\ftriggerEvent\x126\n" +
	"\x06filter\x18\x04 \x01(\v2\x1e.gitprovider.v1.WorkflowFilterR\x06filter\x122\n" +
	"\x05steps\x18\x05 \x03(\v2\x1c.gitprovider.v1.WorkflowStepR\x05steps\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\rStepExecution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vpipeline_id\x18\x03 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\"\x89\x03\n" +
	"\tExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.gitprovider.v1.ExecutionStatusR\x06status\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\x05R\vcurrentStep\x123\n" +
	"\x05steps\x18\x05 \x03(\v2\x1d.gitprovider.v1.StepExecutionR\x05steps\x12#\n" +
	"\rtrigger_event\x18\x06 \x01(\tR\ftriggerEvent\x12\x1e\n" +
	"\n" +
	"repository\x18\a \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\b \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\t \x01(\tR\tcommitSha\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\v \x01(\tR\n" +
	"finishedAt\"\xbc\x01\n" +
	"\x15CreateWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtrigger_event\x18\x02 \x01(\tR\ftriggerEvent\x126\n" +
	"\x06filter\x18\x03 \x01(\v2\x1e.gitprovider.v1.WorkflowFilterR\x06filter\x122\n" +
	"\x05steps\x18\x04 \x03(\v2\x1c.gitprovider.v1.WorkflowStepR\x05steps\"N\n" +
	"\x16CreateWorkflowResponse\x124\n" +
	"\bworkflow\x18\x01 \x01(\v2\x18.gitprovider.v1.WorkflowR\bworkflow\"$\n" +
	"\x12GetWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetWorkflowResponse\x124\n" +
	"\bworkflow\x18\x01 \x01(\v2\x18.gitprovider.v1.WorkflowR\bworkflow\"6\n" +
	"\x14ListWorkflowsRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"O\n" +
	"\x15ListWorkflowsResponse\x126\n" +
	"\tworkflows\x18\x01 \x03(\v2\x18.gitprovider.v1.WorkflowR\tworkflows\"'\n" +
	"\x15DeleteWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x13GetExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"O\n" +
	"\x14GetExecutionResponse\x127\n" +
	"\texecution\x18\x01 \x01(\v2\x19.gitprovider.v1.ExecutionR\texecution\"N\n" +
	"\x15ListExecutionsRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"S\n" +
	"\x16ListExecutionsResponse\x129\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x19.gitprovider.v1.ExecutionR\n" +
	"executions*\xb5\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x01\x12%\n" +
	"!EXECUTION_STATUS_WAITING_FOR_STEP\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x042\x85\x06\n" +
	"\x0fWorkflowService\x12\x80\x01\n" +
	"\x0eCreateWorkflow\x12%.gitprovider.v1.CreateWorkflowRequest\x1a&.gitprovider.v1.CreateWorkflowResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/workflows/create\x12t\n" +
	"\vGetWorkflow\x12\".gitprovider.v1.GetWorkflowRequest\x1a#.gitprovider.v1.GetWorkflowResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/workflows/get\x12{\n" +
	"\rListWorkflows\x12$.gitprovider.v1.ListWorkflowsRequest\x1a%.gitprovider.v1.ListWorkflowsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/workflows/list\x12\x80\x01\n" +
	"\x0eDeleteWorkflow\x12%.gitprovider.v1.DeleteWorkflowRequest\x1a&.gitprovider.v1.DeleteWorkflowResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/workflows/delete\x12x\n" +
	"\fGetExecution\x12#.gitprovider.v1.GetExecutionRequest\x1a$.gitprovider.v1.GetExecutionResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/executions/get\x12\x7f\n" +
	"\x0eListExecutions\x12%.gitprovider.v1.ListExecutionsRequest\x1a&.gitprovider.v1.ListExecutionsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/executions/listB5Z3github.com/runners-high/git-provider/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_v1_workflow_proto_rawDescOnce sync.Once
	file_v1_workflow_proto_rawDescData []byte
)

func file_v1_workflow_proto_rawDescGZIP() []byte {
	file_v1_workflow_proto_rawDescOnce.Do(func() {
		file_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_workflow_proto_rawDesc), len(file_v1_workflow_proto_rawDesc)))
	})
	return file_v1_workflow_proto_rawDescData
}

var file_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_workflow_proto_goTypes = []any{
	(ExecutionStatus)(0),           // 0: gitprovider.v1.ExecutionStatus
	(*WorkflowFilter)(nil),         // 1: gitprovider.v1.WorkflowFilter
	(*WorkflowStep)(nil),           // 2: gitprovider.v1.WorkflowStep
	(*Workflow)(nil),               // 3: gitprovider.v1.Workflow
	(*StepExecution)(nil),          // 4: gitprovider.v1.StepExecution
	(*Execution)(nil),              // 5: gitprovider.v1.Execution
	(*CreateWorkflowRequest)(nil),  // 6: gitprovider.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil), // 7: gitprovider.v1.CreateWorkflowResponse
	(*GetWorkflowRequest)(nil),     // 8: gitprovider.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),    // 9: gitprovider.v1.GetWorkflowResponse
	(*ListWorkflowsRequest)(nil),   // 10: gitprovider.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),  // 11: gitprovider.v1.ListWorkflowsResponse
	(*DeleteWorkflowRequest)(nil),  // 12: gitprovider.v1.DeleteWorkflowRequest
	(*DeleteWorkflowResponse)(nil), // 13: gitprovider.v1.DeleteWorkflowResponse
	(*GetExecutionRequest)(nil),    // 14: gitprovider.v1.GetExecutionRequest
	(*GetExecutionResponse)(nil),   // 15: gitprovider.v1.GetExecutionResponse
	(*ListExecutionsRequest)(nil),  // 16: gitprovider.v1.ListExecutionsRequest
	(*ListExecutionsResponse)(nil), // 17: gitprovider.v1.ListExecutionsResponse
}
var file_v1_workflow_proto_depIdxs = []int32{
	1,  // 0: gitprovider.v1.Workflow.filter:type_name -> gitprovider.v1.WorkflowFilter
	2,  // 1: gitprovider.v1.Workflow.steps:type_name -> gitprovider.v1.WorkflowStep
	0,  // 2: gitprovider.v1.Execution.status:type_name -> gitprovider.v1.ExecutionStatus
	4,  // 3: gitprovider.v1.Execution.steps:type_name -> gitprovider.v1.StepExecution
	1,  // 4: gitprovider.v1.CreateWorkflowRequest.filter:type_name -> gitprovider.v1.WorkflowFilter
	2,  // 5: gitprovider.v1.CreateWorkflowRequest.steps:type_name -> gitprovider.v1.WorkflowStep
	3,  // 6: gitprovider.v1.CreateWorkflowResponse.workflow:type_name -> gitprovider.v1.Workflow
	3,  // 7: gitprovider.v1.GetWorkflowResponse.workflow:type_name -> gitprovider.v1.Workflow
	3,  // 8: gitprovider.v1.ListWorkflowsResponse.workflows:type_name -> gitprovider.v1.Workflow
	5,  // 9: gitprovider.v1.GetExecutionResponse.execution:type_name -> gitprovider.v1.Execution
	5,  // 10: gitprovider.v1.ListExecutionsResponse.executions:type_name -> gitprovider.v1.Execution
	6,  // 11: gitprovider.v1.WorkflowService.CreateWorkflow:input_type -> gitprovider.v1.CreateWorkflowRequest
	8,  // 12: gitprovider.v1.WorkflowService.GetWorkflow:input_type -> gitprovider.v1.GetWorkflowRequest
	10, // 13: gitprovider.v1.WorkflowService.ListWorkflows:input_type -> gitprovider.v1.ListWorkflowsRequest
	12, // 14: gitprovider.v1.WorkflowService.DeleteWorkflow:input_type -> gitprovider.v1.DeleteWorkflowRequest
	14, // 15: gitprovider.v1.WorkflowService.GetExecution:input_type -> gitprovider.v1.GetExecutionRequest
	16, // 16: gitprovider.v1.WorkflowService.ListExecutions:input_type -> gitprovider.v1.ListExecutionsRequest
	7,  // 17: gitprovider.v1.WorkflowService.CreateWorkflow:output_type -> gitprovider.v1.CreateWorkflowResponse
	9,  // 18: gitprovider.v1.WorkflowService.GetWorkflow:output_type -> gitprovider.v1.GetWorkflowResponse
	11, // 19: gitprovider.v1.WorkflowService.ListWorkflows:output_type -> gitprovider.v1.ListWorkflowsResponse
	13, // 20: gitprovider.v1.WorkflowService.DeleteWorkflow:output_type -> gitprovider.v1.DeleteWorkflowResponse
	15, // 21: gitprovider.v1.WorkflowService.GetExecution:output_type -> gitprovider.v1.GetExecutionResponse
	17, // 22: gitprovider.v1.WorkflowService.ListExecutions:output_type -> gitprovider.v1.ListExecutionsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_workflow_proto_init() }
func file_v1_workflow_proto_init() {
	if File_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_workflow_proto_rawDesc), len(file_v1_workflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_workflow_proto_goTypes,
		DependencyIndexes: file_v1_workflow_proto_depIdxs,
		EnumInfos:         file_v1_workflow_proto_enumTypes,
		MessageInfos:      file_v1_workflow_proto_msgTypes,
	}.Build()
	File_v1_workflow_proto = out.File
	file_v1_workflow_proto_goTypes = nil
	file_v1_workflow_proto_depIdxs = nil
}
