// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_proto_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Provider) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_proto_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetProviderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_proto_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{2}
}

func (x *GetProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ListProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderRequest) Reset() {
	*x = ListProviderRequest{}
	mi := &file_proto_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderRequest) ProtoMessage() {}

func (x *ListProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderRequest.ProtoReflect.Descriptor instead.
func (*ListProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{3}
}

var File_proto_provider_proto protoreflect.FileDescriptor

const file_proto_provider_proto_rawDesc = "" +
	"\n" +
	"\x14proto/provider.proto\x12\x05proto\"O\n" +
	"\bProvider\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"(\n" +
	"\x12GetProviderRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"B\n" +
	"\x13GetProviderResponse\x12+\n" +
	"\bprovider\x18\x01 \x01(\v2\x0f.proto.ProviderR\bprovider\"\x15\n" +
	"\x13ListProviderRequest2\x97\x01\n" +
	"\x0fProviderService\x12D\n" +
	"\vGetProvider\x12\x19.proto.GetProviderRequest\x1a\x1a.proto.GetProviderResponse\x12>\n" +
	"\rListProviders\x12\x1a.proto.ListProviderRequest\x1a\x0f.proto.Provider0\x01B$Z\"go-learning/07-grpc-advanced/protob\x06proto3"

var (
	file_proto_provider_proto_rawDescOnce sync.Once
	file_proto_provider_proto_rawDescData []byte
)

func file_proto_provider_proto_rawDescGZIP() []byte {
	file_proto_provider_proto_rawDescOnce.Do(func() {
		file_proto_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_provider_proto_rawDesc), len(file_proto_provider_proto_rawDesc)))
	})
	return file_proto_provider_proto_rawDescData
}

var file_proto_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_provider_proto_goTypes = []any{
	(*Provider)(nil),            // 0: proto.Provider
	(*GetProviderRequest)(nil),  // 1: proto.GetProviderRequest
	(*GetProviderResponse)(nil), // 2: proto.GetProviderResponse
	(*ListProviderRequest)(nil), // 3: proto.ListProviderRequest
}
var file_proto_provider_proto_depIdxs = []int32{
	0, // 0: proto.GetProviderResponse.provider:type_name -> proto.Provider
	1, // 1: proto.ProviderService.GetProvider:input_type -> proto.GetProviderRequest
	3, // 2: proto.ProviderService.ListProviders:input_type -> proto.ListProviderRequest
	2, // 3: proto.ProviderService.GetProvider:output_type -> proto.GetProviderResponse
	0, // 4: proto.ProviderService.ListProviders:output_type -> proto.Provider
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_provider_proto_init() }
func file_proto_provider_proto_init() {
	if File_proto_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_provider_proto_rawDesc), len(file_proto_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_provider_proto_goTypes,
		DependencyIndexes: file_proto_provider_proto_depIdxs,
		MessageInfos:      file_proto_provider_proto_msgTypes,
	}.Build()
	File_proto_provider_proto = out.File
	file_proto_provider_proto_goTypes = nil
	file_proto_provider_proto_depIdxs = nil
}
