# Istio Sidecar Mode - Local Development
# Usage: helm install istiod istio/istiod -n istio-system -f istio-values.yaml

meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    holdApplicationUntilProxyStarts: true
  enableAutoMtls: true

global:
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi

pilot:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
