### Nexus Health Check
GET http://localhost:8081/service/rest/v1/status
Accept: application/json

### Nexus Status Check (writable)
GET http://localhost:8081/service/rest/v1/status/writable
Accept: application/json

### System Information
GET http://localhost:8081/service/rest/v1/status/check
Authorization: Basic YWRtaW46YWRtaW4xMjM=
Accept: application/json
