// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/v1/provider.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_GITHUB      ProviderType = 1
	ProviderType_PROVIDER_TYPE_GITLAB      ProviderType = 2
	ProviderType_PROVIDER_TYPE_BITBUCKET   ProviderType = 3
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_GITHUB",
		2: "PROVIDER_TYPE_GITLAB",
		3: "PROVIDER_TYPE_BITBUCKET",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_GITHUB":      1,
		"PROVIDER_TYPE_GITLAB":      2,
		"PROVIDER_TYPE_BITBUCKET":   3,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_provider_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{0}
}

type GitHubConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // 선택: Enterprise URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubConfig) Reset() {
	*x = GitHubConfig{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubConfig) ProtoMessage() {}

func (x *GitHubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubConfig.ProtoReflect.Descriptor instead.
func (*GitHubConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GitHubConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitHubConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type GitLabConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // 선택: Self-hosted URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLabConfig) Reset() {
	*x = GitLabConfig{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLabConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLabConfig) ProtoMessage() {}

func (x *GitLabConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLabConfig.ProtoReflect.Descriptor instead.
func (*GitLabConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GitLabConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitLabConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type BitbucketConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API Token 인증 (2025년 9월 9일부터 권장)
	ApiToken      string `protobuf:"bytes,1,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"` // API Token (ATAT... 형식)
	Workspace     string `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`               // 선택: Workspace 이름
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitbucketConfig) Reset() {
	*x = BitbucketConfig{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitbucketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitbucketConfig) ProtoMessage() {}

func (x *BitbucketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitbucketConfig.ProtoReflect.Descriptor instead.
func (*BitbucketConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *BitbucketConfig) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *BitbucketConfig) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

// 프로바이더 설정 (하나만 선택)
type ProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*ProviderConfig_Github
	//	*ProviderConfig_Gitlab
	//	*ProviderConfig_Bitbucket
	Config        isProviderConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderConfig) GetConfig() isProviderConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProviderConfig) GetGithub() *GitHubConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Github); ok {
			return x.Github
		}
	}
	return nil
}

func (x *ProviderConfig) GetGitlab() *GitLabConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Gitlab); ok {
			return x.Gitlab
		}
	}
	return nil
}

func (x *ProviderConfig) GetBitbucket() *BitbucketConfig {
	if x != nil {
		if x, ok := x.Config.(*ProviderConfig_Bitbucket); ok {
			return x.Bitbucket
		}
	}
	return nil
}

type isProviderConfig_Config interface {
	isProviderConfig_Config()
}

type ProviderConfig_Github struct {
	Github *GitHubConfig `protobuf:"bytes,1,opt,name=github,proto3,oneof"`
}

type ProviderConfig_Gitlab struct {
	Gitlab *GitLabConfig `protobuf:"bytes,2,opt,name=gitlab,proto3,oneof"`
}

type ProviderConfig_Bitbucket struct {
	Bitbucket *BitbucketConfig `protobuf:"bytes,3,opt,name=bitbucket,proto3,oneof"`
}

func (*ProviderConfig_Github) isProviderConfig_Config() {}

func (*ProviderConfig_Gitlab) isProviderConfig_Config() {}

func (*ProviderConfig_Bitbucket) isProviderConfig_Config() {}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      ProviderType    `protobuf:"varint,3,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	Config    *ProviderConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt string          `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *Provider) GetConfig() *ProviderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Provider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Provider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RegisterProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType    `protobuf:"varint,2,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	Config        *ProviderConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderRequest) Reset() {
	*x = RegisterProviderRequest{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderRequest) ProtoMessage() {}

func (x *RegisterProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterProviderRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *RegisterProviderRequest) GetConfig() *ProviderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegisterProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderResponse) Reset() {
	*x = RegisterProviderResponse{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderResponse) ProtoMessage() {}

func (x *RegisterProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *GetProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProviderType           `protobuf:"varint,1,opt,name=type,proto3,enum=gitprovider.v1.ProviderType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ListProvidersRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderResponse) Reset() {
	*x = DeleteProviderResponse{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderResponse) ProtoMessage() {}

func (x *DeleteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,6,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,7,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	Private       bool                   `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *Repository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type ListRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderConfig        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // 프로바이더 설정 (매 요청마다 전달)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *ListRepositoriesRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_api_proto_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

var File_api_proto_v1_provider_proto protoreflect.FileDescriptor

const file_api_proto_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/provider.proto\x12\x0egitprovider.v1\x1a\x1cgoogle/api/annotations.proto\"?\n" +
	"\fGitHubConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"?\n" +
	"\fGitLabConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"L\n" +
	"\x0fBitbucketConfig\x12\x1b\n" +
	"\tapi_token\x18\x01 \x01(\tR\bapiToken\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"\xcb\x01\n" +
	"\x0eProviderConfig\x126\n" +
	"\x06github\x18\x01 \x01(\v2\x1c.gitprovider.v1.GitHubConfigH\x00R\x06github\x126\n" +
	"\x06gitlab\x18\x02 \x01(\v2\x1c.gitprovider.v1.GitLabConfigH\x00R\x06gitlab\x12?\n" +
	"\tbitbucket\x18\x03 \x01(\v2\x1f.gitprovider.v1.BitbucketConfigH\x00R\tbitbucketB\b\n" +
	"\x06config\"\xd6\x01\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x97\x01\n" +
	"\x17RegisterProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\x06config\"P\n" +
	"\x18RegisterProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.gitprovider.v1.ProviderR\bprovider\"$\n" +
	"\x12GetProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.gitprovider.v1.ProviderR\bprovider\"H\n" +
	"\x14ListProvidersRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.gitprovider.v1.ProviderTypeR\x04type\"O\n" +
	"\x15ListProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.gitprovider.v1.ProviderR\tproviders\"'\n" +
	"\x15DeleteProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xdf\x01\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tclone_url\x18\x06 \x01(\tR\bcloneUrl\x12%\n" +
	"\x0edefault_branch\x18\a \x01(\tR\rdefaultBranch\x12\x18\n" +
	"\aprivate\x18\b \x01(\bR\aprivate\"U\n" +
	"\x17ListRepositoriesRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\v2\x1e.gitprovider.v1.ProviderConfigR\bprovider\"Z\n" +
	"\x18ListRepositoriesResponse\x12>\n" +
	"\frepositories\x18\x01 \x03(\v2\x1a.gitprovider.v1.RepositoryR\frepositories*~\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITHUB\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITLAB\x10\x02\x12\x1b\n" +
	"\x17PROVIDER_TYPE_BITBUCKET\x10\x032\xf8\x03\n" +
	"\x0fProviderService\x12\x7f\n" +
	"\x10RegisterProvider\x12'.gitprovider.v1.RegisterProviderRequest\x1a(.gitprovider.v1.RegisterProviderResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/providers\x12r\n" +
	"\vGetProvider\x12\".gitprovider.v1.GetProviderRequest\x1a#.gitprovider.v1.GetProviderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/providers/{id}\x12s\n" +
	"\rListProviders\x12$.gitprovider.v1.ListProvidersRequest\x1a%.gitprovider.v1.ListProvidersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/providers\x12{\n" +
	"\x0eDeleteProvider\x12%.gitprovider.v1.DeleteProviderRequest\x1a&.gitprovider.v1.DeleteProviderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/providers/{id}2\x96\x01\n" +
	"\n" +
	"GitService\x12\x87\x01\n" +
	"\x10ListRepositories\x12'.gitprovider.v1.ListRepositoriesRequest\x1a(.gitprovider.v1.ListRepositoriesResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/repositories/listB5Z3github.com/runners-high/git-provider/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_api_proto_v1_provider_proto_rawDescOnce sync.Once
	file_api_proto_v1_provider_proto_rawDescData []byte
)

func file_api_proto_v1_provider_proto_rawDescGZIP() []byte {
	file_api_proto_v1_provider_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_provider_proto_rawDesc), len(file_api_proto_v1_provider_proto_rawDesc)))
	})
	return file_api_proto_v1_provider_proto_rawDescData
}

var file_api_proto_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_v1_provider_proto_goTypes = []any{
	(ProviderType)(0),                // 0: gitprovider.v1.ProviderType
	(*GitHubConfig)(nil),             // 1: gitprovider.v1.GitHubConfig
	(*GitLabConfig)(nil),             // 2: gitprovider.v1.GitLabConfig
	(*BitbucketConfig)(nil),          // 3: gitprovider.v1.BitbucketConfig
	(*ProviderConfig)(nil),           // 4: gitprovider.v1.ProviderConfig
	(*Provider)(nil),                 // 5: gitprovider.v1.Provider
	(*RegisterProviderRequest)(nil),  // 6: gitprovider.v1.RegisterProviderRequest
	(*RegisterProviderResponse)(nil), // 7: gitprovider.v1.RegisterProviderResponse
	(*GetProviderRequest)(nil),       // 8: gitprovider.v1.GetProviderRequest
	(*GetProviderResponse)(nil),      // 9: gitprovider.v1.GetProviderResponse
	(*ListProvidersRequest)(nil),     // 10: gitprovider.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),    // 11: gitprovider.v1.ListProvidersResponse
	(*DeleteProviderRequest)(nil),    // 12: gitprovider.v1.DeleteProviderRequest
	(*DeleteProviderResponse)(nil),   // 13: gitprovider.v1.DeleteProviderResponse
	(*Repository)(nil),               // 14: gitprovider.v1.Repository
	(*ListRepositoriesRequest)(nil),  // 15: gitprovider.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 16: gitprovider.v1.ListRepositoriesResponse
}
var file_api_proto_v1_provider_proto_depIdxs = []int32{
	1,  // 0: gitprovider.v1.ProviderConfig.github:type_name -> gitprovider.v1.GitHubConfig
	2,  // 1: gitprovider.v1.ProviderConfig.gitlab:type_name -> gitprovider.v1.GitLabConfig
	3,  // 2: gitprovider.v1.ProviderConfig.bitbucket:type_name -> gitprovider.v1.BitbucketConfig
	0,  // 3: gitprovider.v1.Provider.type:type_name -> gitprovider.v1.ProviderType
	4,  // 4: gitprovider.v1.Provider.config:type_name -> gitprovider.v1.ProviderConfig
	0,  // 5: gitprovider.v1.RegisterProviderRequest.type:type_name -> gitprovider.v1.ProviderType
	4,  // 6: gitprovider.v1.RegisterProviderRequest.config:type_name -> gitprovider.v1.ProviderConfig
	5,  // 7: gitprovider.v1.RegisterProviderResponse.provider:type_name -> gitprovider.v1.Provider
	5,  // 8: gitprovider.v1.GetProviderResponse.provider:type_name -> gitprovider.v1.Provider
	0,  // 9: gitprovider.v1.ListProvidersRequest.type:type_name -> gitprovider.v1.ProviderType
	5,  // 10: gitprovider.v1.ListProvidersResponse.providers:type_name -> gitprovider.v1.Provider
	4,  // 11: gitprovider.v1.ListRepositoriesRequest.provider:type_name -> gitprovider.v1.ProviderConfig
	14, // 12: gitprovider.v1.ListRepositoriesResponse.repositories:type_name -> gitprovider.v1.Repository
	6,  // 13: gitprovider.v1.ProviderService.RegisterProvider:input_type -> gitprovider.v1.RegisterProviderRequest
	8,  // 14: gitprovider.v1.ProviderService.GetProvider:input_type -> gitprovider.v1.GetProviderRequest
	10, // 15: gitprovider.v1.ProviderService.ListProviders:input_type -> gitprovider.v1.ListProvidersRequest
	12, // 16: gitprovider.v1.ProviderService.DeleteProvider:input_type -> gitprovider.v1.DeleteProviderRequest
	15, // 17: gitprovider.v1.GitService.ListRepositories:input_type -> gitprovider.v1.ListRepositoriesRequest
	7,  // 18: gitprovider.v1.ProviderService.RegisterProvider:output_type -> gitprovider.v1.RegisterProviderResponse
	9,  // 19: gitprovider.v1.ProviderService.GetProvider:output_type -> gitprovider.v1.GetProviderResponse
	11, // 20: gitprovider.v1.ProviderService.ListProviders:output_type -> gitprovider.v1.ListProvidersResponse
	13, // 21: gitprovider.v1.ProviderService.DeleteProvider:output_type -> gitprovider.v1.DeleteProviderResponse
	16, // 22: gitprovider.v1.GitService.ListRepositories:output_type -> gitprovider.v1.ListRepositoriesResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_v1_provider_proto_init() }
func file_api_proto_v1_provider_proto_init() {
	if File_api_proto_v1_provider_proto != nil {
		return
	}
	file_api_proto_v1_provider_proto_msgTypes[3].OneofWrappers = []any{
		(*ProviderConfig_Github)(nil),
		(*ProviderConfig_Gitlab)(nil),
		(*ProviderConfig_Bitbucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_provider_proto_rawDesc), len(file_api_proto_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_v1_provider_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_provider_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_provider_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_provider_proto_msgTypes,
	}.Build()
	File_api_proto_v1_provider_proto = out.File
	file_api_proto_v1_provider_proto_goTypes = nil
	file_api_proto_v1_provider_proto_depIdxs = nil
}
