// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/learning.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// LearningServiceClient is the client API for LearningService service.
type LearningServiceClient interface {
	// Unary RPC
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	TestError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	TestDelay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*DelayResponse, error)
	// Server Streaming RPC
	StreamNumbers(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (LearningService_StreamNumbersClient, error)
	StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (LearningService_StreamLogsClient, error)
	DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (LearningService_DownloadFileClient, error)
	// Client Streaming RPC
	SumNumbers(ctx context.Context, opts ...grpc.CallOption) (LearningService_SumNumbersClient, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (LearningService_UploadFileClient, error)
	// Bidirectional Streaming RPC
	Chat(ctx context.Context, opts ...grpc.CallOption) (LearningService_ChatClient, error)
	Echo(ctx context.Context, opts ...grpc.CallOption) (LearningService_EchoClient, error)
}

type learningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearningServiceClient(cc grpc.ClientConnInterface) LearningServiceClient {
	return &learningServiceClient{cc}
}

func (c *learningServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/learning.v1.LearningService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/learning.v1.LearningService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) TestError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/learning.v1.LearningService/TestError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) TestDelay(ctx context.Context, in *DelayRequest, opts ...grpc.CallOption) (*DelayResponse, error) {
	out := new(DelayResponse)
	err := c.cc.Invoke(ctx, "/learning.v1.LearningService/TestDelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) StreamNumbers(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (LearningService_StreamNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[0], "/learning.v1.LearningService/StreamNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceStreamNumbersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LearningService_StreamNumbersClient interface {
	Recv() (*NumberResponse, error)
	grpc.ClientStream
}

type learningServiceStreamNumbersClient struct {
	grpc.ClientStream
}

func (x *learningServiceStreamNumbersClient) Recv() (*NumberResponse, error) {
	m := new(NumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (LearningService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[1], "/learning.v1.LearningService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LearningService_StreamLogsClient interface {
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type learningServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *learningServiceStreamLogsClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (LearningService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[2], "/learning.v1.LearningService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LearningService_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type learningServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *learningServiceDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) SumNumbers(ctx context.Context, opts ...grpc.CallOption) (LearningService_SumNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[3], "/learning.v1.LearningService/SumNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceSumNumbersClient{stream}
	return x, nil
}

type LearningService_SumNumbersClient interface {
	Send(*NumberValue) error
	CloseAndRecv() (*SumResponse, error)
	grpc.ClientStream
}

type learningServiceSumNumbersClient struct {
	grpc.ClientStream
}

func (x *learningServiceSumNumbersClient) Send(m *NumberValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *learningServiceSumNumbersClient) CloseAndRecv() (*SumResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (LearningService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[4], "/learning.v1.LearningService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceUploadFileClient{stream}
	return x, nil
}

type LearningService_UploadFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type learningServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *learningServiceUploadFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *learningServiceUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (LearningService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[5], "/learning.v1.LearningService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceChatClient{stream}
	return x, nil
}

type LearningService_ChatClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type learningServiceChatClient struct {
	grpc.ClientStream
}

func (x *learningServiceChatClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *learningServiceChatClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *learningServiceClient) Echo(ctx context.Context, opts ...grpc.CallOption) (LearningService_EchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &LearningService_ServiceDesc.Streams[6], "/learning.v1.LearningService/Echo", opts...)
	if err != nil {
		return nil, err
	}
	x := &learningServiceEchoClient{stream}
	return x, nil
}

type LearningService_EchoClient interface {
	Send(*EchoRequest) error
	Recv() (*EchoResponse, error)
	grpc.ClientStream
}

type learningServiceEchoClient struct {
	grpc.ClientStream
}

func (x *learningServiceEchoClient) Send(m *EchoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *learningServiceEchoClient) Recv() (*EchoResponse, error) {
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LearningServiceServer is the server API for LearningService service.
type LearningServiceServer interface {
	// Unary RPC
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	TestError(context.Context, *ErrorRequest) (*ErrorResponse, error)
	TestDelay(context.Context, *DelayRequest) (*DelayResponse, error)
	// Server Streaming RPC
	StreamNumbers(*NumberRequest, LearningService_StreamNumbersServer) error
	StreamLogs(*LogRequest, LearningService_StreamLogsServer) error
	DownloadFile(*FileRequest, LearningService_DownloadFileServer) error
	// Client Streaming RPC
	SumNumbers(LearningService_SumNumbersServer) error
	UploadFile(LearningService_UploadFileServer) error
	// Bidirectional Streaming RPC
	Chat(LearningService_ChatServer) error
	Echo(LearningService_EchoServer) error
	mustEmbedUnimplementedLearningServiceServer()
}

// UnimplementedLearningServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLearningServiceServer struct {
}

func (UnimplementedLearningServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedLearningServiceServer) Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedLearningServiceServer) TestError(context.Context, *ErrorRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestError not implemented")
}
func (UnimplementedLearningServiceServer) TestDelay(context.Context, *DelayRequest) (*DelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestDelay not implemented")
}
func (UnimplementedLearningServiceServer) StreamNumbers(*NumberRequest, LearningService_StreamNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNumbers not implemented")
}
func (UnimplementedLearningServiceServer) StreamLogs(*LogRequest, LearningService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLearningServiceServer) DownloadFile(*FileRequest, LearningService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedLearningServiceServer) SumNumbers(LearningService_SumNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method SumNumbers not implemented")
}
func (UnimplementedLearningServiceServer) UploadFile(LearningService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedLearningServiceServer) Chat(LearningService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLearningServiceServer) Echo(LearningService_EchoServer) error {
	return status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedLearningServiceServer) mustEmbedUnimplementedLearningServiceServer() {}

// UnsafeLearningServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeLearningServiceServer interface {
	mustEmbedUnimplementedLearningServiceServer()
}

func RegisterLearningServiceServer(s grpc.ServiceRegistrar, srv LearningServiceServer) {
	s.RegisterService(&LearningService_ServiceDesc, srv)
}

func _LearningService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/learning.v1.LearningService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/learning.v1.LearningService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_TestError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).TestError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/learning.v1.LearningService/TestError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).TestError(ctx, req.(*ErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_TestDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).TestDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/learning.v1.LearningService/TestDelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).TestDelay(ctx, req.(*DelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_StreamNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearningServiceServer).StreamNumbers(m, &learningServiceStreamNumbersServer{stream})
}

type LearningService_StreamNumbersServer interface {
	Send(*NumberResponse) error
	grpc.ServerStream
}

type learningServiceStreamNumbersServer struct {
	grpc.ServerStream
}

func (x *learningServiceStreamNumbersServer) Send(m *NumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LearningService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearningServiceServer).StreamLogs(m, &learningServiceStreamLogsServer{stream})
}

type LearningService_StreamLogsServer interface {
	Send(*LogResponse) error
	grpc.ServerStream
}

type learningServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *learningServiceStreamLogsServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LearningService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LearningServiceServer).DownloadFile(m, &learningServiceDownloadFileServer{stream})
}

type LearningService_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type learningServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *learningServiceDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _LearningService_SumNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LearningServiceServer).SumNumbers(&learningServiceSumNumbersServer{stream})
}

type LearningService_SumNumbersServer interface {
	SendAndClose(*SumResponse) error
	Recv() (*NumberValue, error)
	grpc.ServerStream
}

type learningServiceSumNumbersServer struct {
	grpc.ServerStream
}

func (x *learningServiceSumNumbersServer) SendAndClose(m *SumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *learningServiceSumNumbersServer) Recv() (*NumberValue, error) {
	m := new(NumberValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LearningService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LearningServiceServer).UploadFile(&learningServiceUploadFileServer{stream})
}

type LearningService_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type learningServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *learningServiceUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *learningServiceUploadFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LearningService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LearningServiceServer).Chat(&learningServiceChatServer{stream})
}

type LearningService_ChatServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type learningServiceChatServer struct {
	grpc.ServerStream
}

func (x *learningServiceChatServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *learningServiceChatServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LearningService_Echo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LearningServiceServer).Echo(&learningServiceEchoServer{stream})
}

type LearningService_EchoServer interface {
	Send(*EchoResponse) error
	Recv() (*EchoRequest, error)
	grpc.ServerStream
}

type learningServiceEchoServer struct {
	grpc.ServerStream
}

func (x *learningServiceEchoServer) Send(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *learningServiceEchoServer) Recv() (*EchoRequest, error) {
	m := new(EchoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LearningService_ServiceDesc is the grpc.ServiceDesc for LearningService service.
var LearningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "learning.v1.LearningService",
	HandlerType: (*LearningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _LearningService_SayHello_Handler,
		},
		{
			MethodName: "Calculate",
			Handler:    _LearningService_Calculate_Handler,
		},
		{
			MethodName: "TestError",
			Handler:    _LearningService_TestError_Handler,
		},
		{
			MethodName: "TestDelay",
			Handler:    _LearningService_TestDelay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNumbers",
			Handler:       _LearningService_StreamNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _LearningService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _LearningService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SumNumbers",
			Handler:       _LearningService_SumNumbers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _LearningService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _LearningService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Echo",
			Handler:       _LearningService_Echo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/learning.proto",
}
